### ISSUE TITLE
error log spamming log-file

### ISSUE THREAD

**Issue by GatoPharaoh** [bbernhard/signal-cli-rest-api#186] opened 2021-12-04 15:05 UTC
### The problem

Hi

I've been using the docker container for about 6 weeks with success. after a power outage in my house, signal suddenly stopped working with the error message 
` time="2021-12-04T14:51:13Z" level=error msg="Couldn't read data for number +4xxxxxxxxxxxx: EOF. Is the number properly registered?`

while i have not yet checked what the issue behind the error message is, i noticed that the container is spamming the log with the error message.
by spamming i mean that the error is logged hundreds of times per second leading to a huge log file. in my case, the log file got to a whopping 360 gigabyte over a course of about 12 hours when disk space finally ran out and paralyzed the entire system.

question: is this normal behavior or is there anything I can do to reduce the amount logging if this issue every reoccures in the future? (apart from limiting log size in docker itself)

thank you!

### Are you using the latest released version?

- [X] Yes

### Have you read the troubleshooting page?

- [X] Yes

### What type of installation are you running?

signal-cli-rest-api Docker Container

### In which mode are you using the docker container?

JSON-RPC Mode

### What's the architecture of your host system?

x86-64

**Comment by GatoPharaoh** [comment] 2021-12-04 15:20
this is what startup of the container looks like - a few seconds after this the error logging mentioned above commences.

```
Starting signal_signal-cli-rest-api_1_5acca8a0c7c9 ... done
Attaching to signal_signal-cli-rest-api_1_5acca8a0c7c9
signal-cli-rest-api_1_5acca8a0c7c9 | + set -e
signal-cli-rest-api_1_5acca8a0c7c9 | + [ -z /home/.local/share/signal-cli ]
signal-cli-rest-api_1_5acca8a0c7c9 | + chown 1000:1000 -R /home/.local/share/signal-cli
signal-cli-rest-api_1_5acca8a0c7c9 | + cat
signal-cli-rest-api_1_5acca8a0c7c9 | + cap_prefix=-cap_
signal-cli-rest-api_1_5acca8a0c7c9 | + cat /proc/sys/kernel/cap_last_cap
signal-cli-rest-api_1_5acca8a0c7c9 | + seq -s ,-cap_ 0 40
signal-cli-rest-api_1_5acca8a0c7c9 | + caps=-cap_0,-cap_1,-cap_2,-cap_3,-cap_4,-cap_5,-cap_6,-cap_7,-cap_8,-cap_9,-cap_10,-cap_11,-cap_12,-cap_13,-cap_14,-cap_15,-cap_16,-cap_17,-cap_18,-cap_19,-cap_20,-cap_21,-cap_22,-cap_23,-cap_24,-cap_25,-cap_26,-cap_27,-cap_28,-cap_29,-cap_30,-cap_31,-cap_32,-cap_33,-cap_34,-cap_35,-cap_36,-cap_37,-cap_38,-cap_39,-cap_40
signal-cli-rest-api_1_5acca8a0c7c9 | + [ json-rpc = json-rpc ]
signal-cli-rest-api_1_5acca8a0c7c9 | + /usr/bin/jsonrpc2-helper
signal-cli-rest-api_1_5acca8a0c7c9 | time="2021-12-04T15:17:04Z" level=info msg="Found number +4xxxxxxxxxx and added it to jsonrpc2.yml"
signal-cli-rest-api_1_5acca8a0c7c9 | + service supervisor start
signal-cli-rest-api_1_5acca8a0c7c9 | Starting supervisor: supervisord.
signal-cli-rest-api_1_5acca8a0c7c9 | + supervisorctl start all
signal-cli-rest-api_1_5acca8a0c7c9 | + exec setpriv --reuid=1000 --regid=1000 --init-groups --inh-caps=-cap_0,-cap_1,-cap_2,-cap_3,-cap_4,-cap_5,-cap_6,-cap_7,-cap_8,-cap_9,-cap_10,-cap_11,-cap_12,-cap_13,-cap_14,-cap_15,-cap_16,-cap_17,-cap_18,-cap_19,-cap_20,-cap_21,-cap_22,-cap_23,-cap_24,-cap_25,-cap_26,-cap_27,-cap_28,-cap_29,-cap_30,-cap_31,-cap_32,-cap_33,-cap_34,-cap_35,-cap_36,-cap_37,-cap_38,-cap_39,-cap_40 signal-cli-rest-api -signal-cli-config=/home/.local/share/signal-cli

```

**Comment by bbernhard** [comment] 2021-12-04 15:28
Could you please connect to the running docker container with `docker exec -it <container id> /bin/bash` and check the `/var/log/signal-cli-json-rpc-1/` folder for log files. Do you see any error in there? Please also check the log file `/var/log/supervisor/supervisord.log`

**Comment by GatoPharaoh** [comment] 2021-12-04 15:45
_/var/log/signal-cli-json-rpc-1/_
```

Error loading state file for user +4xxxxxxxxxxxx: No content to map due to end-of-input
 at [Source: (FileInputStream); line: 1, column: 0] (MismatchedInputException)
Error loading state file for user +4xxxxxxxxxxxx: No content to map due to end-of-input
 at [Source: (FileInputStream); line: 1, column: 0] (MismatchedInputException)
Error loading state file for user +4xxxxxxxxxxxx: No content to map due to end-of-input
 at [Source: (FileInputStream); line: 1, column: 0] (MismatchedInputException)
Error loading state file for user +4xxxxxxxxxxxx: No content to map due to end-of-input
 at [Source: (FileInputStream); line: 1, column: 0] (MismatchedInputException)
```

_/var/log/supervisor/supervisord.log_
```

2021-12-04 15:39:14,680 INFO Included extra file "/etc/supervisor/conf.d/signal-cli-json-rpc-1.conf" during parsing
2021-12-04 15:39:14,989 INFO RPC interface 'supervisor' initialized
2021-12-04 15:39:14,989 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2021-12-04 15:39:14,991 INFO daemonizing the supervisord process
2021-12-04 15:39:14,993 INFO supervisord started with pid 26
2021-12-04 15:39:15,339 INFO spawned: 'signal-cli-json-rpc-1' with pid 33
2021-12-04 15:39:16,349 INFO success: signal-cli-json-rpc-1 entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2021-12-04 15:39:26,495 INFO exited: signal-cli-json-rpc-1 (exit status 2; not expected)
2021-12-04 15:39:27,498 INFO spawned: 'signal-cli-json-rpc-1' with pid 76
2021-12-04 15:39:28,500 INFO success: signal-cli-json-rpc-1 entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)




```

**Comment by bbernhard** [comment] 2021-12-04 16:19
looks like `signal-cli` can't read its config file anymore. I guess this will probably be fixed by re-registering the number. But it would be interesting why it ended in this state in the first place (maybe the `signal-cli` config file got corrupted during the power outage?) Could you please try to switch to normal/native mode and test whether this mode is still working?

**Comment by GatoPharaoh** [comment] 2021-12-04 16:55
switching to normal and native mode does stop the log spamming. nevertheless, messages cannot be send
api-call returns:
 `{"error":"Error loading state file for user +4xxxxxxxxxxx: No content to map due to end-of-input\n at [Source: (FileInputStream); line: 1, column: 0] (MismatchedInputException)"`

I'l´l re-register the number and compare the files in /data to see if I can find any file that got corrupted.

Recapitulating what I did yesterday, signal actually still worked while the log file already took all the available space. I rebooted while there was no space left (as I didn't know at that point that the log took it all) and then signal stopped working. 
Possible that something important couldn't be saved before the reboot as no space was left on device?

**Comment by bbernhard** [comment] 2021-12-04 17:06
> Recapitulating what I did yesterday after the power outage, signal actually still worked while the log file already took all the available space. I rebooted while there was no space left (as I didn't know at that point that the log took it all) and then signal stopped working.

That's odd. The error message `Couldn't read data for number` should only appear in case of a `signal-cli`error. :thinking: 

 > I'll re-register the number and compare the files in /data to see if I can find any file that got corrupted.
 
 That would be interesting :+1: 
 
 In any case, the logging problem is definitely something that should be fixed! I would still prefer a regular log message, instead of a one-shot error message, but we should definitely reduce the logging frequency!

**Comment by GatoPharaoh** [comment] 2021-12-04 22:22
update:

i deleted the entire config folder and re-registered the number. started the docker in normal mode. was able to send a message.
stopped the container, changed to json-rpc, restarted the container and it works!

comparing the old with the new config folder, i can see the following differences:

`\signal-cli-config\data\+4xxxxxxxxxxx.d\ `
contains a file named `recipients-store`
while the old file is completely empty, the new one does contain info (about one recipient)

`\signal-cli-config\data\+4xxxxxxxxxxx.d\sessions\`
old and new folder contain 4 files (named `2_1` `2_2` `2_3` and `2_4`)
files in the old folder are emtpy (0B size), files in the new folder are around 380B in size

apart from these findings, old and new config files look identical in naming and file size

**Comment by bbernhard** [comment] 2021-12-05 17:10
Initially I was pretty sure that the error was caused by `signal-cli`. But as you've mentioned that the REST API was working until you had to reboot, I am not 100% sure anymore. Unfortunately, I do not have an explanation right now what could have caused your issues. The extensive logging was definitely wrong (sorry for that!) and will be fixed with the next release. Instead of logging the error seversal hundred times per second, the message will be logged every 5 minutes as long as the error condition persists. 

I mean you could open an issue in the [signal-cli](https://github.com/AsamK/signal-cli) repository, but not sure if that helps much. Even if the config file/folders are somehow corrupt, we do not know if that was already the case before the reboot or was a result of the reboot/out of memory. But with the changes to the logging you shouldn't run out of memory again. So, if this issue happens again, we should be able to better investigate it (as we can rule out the forced reboot due to out of memory condition).

Sorry for not being any more help!

**Comment by GatoPharaoh** [comment] 2021-12-06 18:34
all good, you've been very helpful.

my case may just be a weird coincidence combined with the logging bug. I'll tinker with the config files on a separate system to see if I can reproduce the issue.

**Closed** 2021-12-06 18:35 UTC
