### ISSUE TITLE
Number not registered with JSON-RPC

### ISSUE THREAD

**Issue by Cangoo** [bbernhard/signal-cli-rest-api#444] opened 2023-11-07 14:39 UTC
### The problem

I made a small automation in homeassistant (which is running in a docker container) where a sensor as a trigger is sending a message with Signal using this signal-cli-rest-api. 

While this works fine in "normal"-mode, But I get an error in "json-rpc"-mode:
Number not registered with JSON-RPC

Any idea what the problem might be? I'm connecting from homeassistant to the signal-cli-rest-api over the url: 
"http://signal-cli-rest-api:8080"

The container for the signal-cli-rest-api got the correct container_name: signal-cli-rest-api (to be accessible under this hostname), and both containers (homeassistant and signal-cli-rest-api) are in the same docker-network.

I found this issue:
https://github.com/bbernhard/signal-cli-rest-api/issues/213
but the number used as "the sender number" in homeassistant wasn't linked somehow but freshly registered with this API. And (as I said): It works fine in normal-mode.

### Are you using the latest released version?

- [X] Yes

### Have you read the troubleshooting page?

- [X] Yes

### What type of installation are you running?

signal-cli-rest-api Docker Container

### In which mode are you using the docker container?

JSON-RPC Mode

### What's the architecture of your host system?

arm64

**Comment by Cangoo** [comment] 2023-11-07 14:56
Ah found the solution here: https://github.com/bbernhard/signal-cli-rest-api/issues/340#issuecomment-1792910871

You have to manuelly edit the file in /signal/cli/config/data/<randomnumber> and put your number in the field username as well. Then restart the container. Works now.

**Comment by dan-s-github** [comment] 2023-11-08 08:00
I use the hass add-on in home assistant and connected to the docker container using

```
docker -it <containerId> /bin/bash
sudo signal-cli
cat (random number)
```
shows empty username

tried editing using vi or vim but both don't seem to be installed in container.
Any clue on how to update the username from inside the container?

**Comment by RJ-Make** [comment] 2023-11-08 23:19
Not sure if it's related, Just update to .70 from .68 and now I'm getting this error.  I really need to learn to STOP updating when stuff works... 
```

2023-11-08 18:15:35 signal-cli-rest-api  | + set -e
2023-11-08 18:15:35 signal-cli-rest-api  | + [ -z /home/.local/share/signal-cli ]
2023-11-08 18:15:35 signal-cli-rest-api  | + usermod -u 1000 signal-api
2023-11-08 18:15:35 signal-cli-rest-api  | usermod: no changes
2023-11-08 18:15:35 signal-cli-rest-api  | + groupmod -g 1000 signal-api
2023-11-08 18:15:35 signal-cli-rest-api  | + chown 1000:1000 -R /home/.local/share/signal-cli
2023-11-08 18:15:35 signal-cli-rest-api  | + cat
2023-11-08 18:15:35 signal-cli-rest-api  | + cap_prefix=-cap_
2023-11-08 18:15:35 signal-cli-rest-api  | + cat /proc/sys/kernel/cap_last_cap
2023-11-08 18:15:35 signal-cli-rest-api  | + seq -s ,-cap_ 0 40
2023-11-08 18:15:35 signal-cli-rest-api  | + caps=-cap_0,-cap_1,-cap_2,-cap_3,-cap_4,-cap_5,-cap_6,-cap_7,-cap_8,-cap_9,-cap_10,-cap_11,-cap_12,-cap_13,-cap_14,-cap_15,-cap_16,-cap_17,-cap_18,-cap_19,-cap_20,-cap_21,-cap_22,-cap_23,-cap_24,-cap_25,-cap_26,-cap_27,-cap_28,-cap_29,-cap_30,-cap_31,-cap_32,-cap_33,-cap_34,-cap_35,-cap_36,-cap_37,-cap_38,-cap_39,-cap_40
2023-11-08 18:15:35 signal-cli-rest-api  | + [ json-rpc = json-rpc ]
2023-11-08 18:15:35 signal-cli-rest-api  | + /usr/bin/jsonrpc2-helper
2023-11-08 18:15:35 signal-cli-rest-api  | time="2023-11-08T23:15:35Z" level=info msg="Found number  and added it to jsonrpc2.yml"
2023-11-08 18:15:35 signal-cli-rest-api  | + service supervisor start
2023-11-08 18:15:36 signal-cli-rest-api  | Starting supervisor: supervisord.
2023-11-08 18:15:36 signal-cli-rest-api  | + supervisorctl start all
2023-11-08 18:15:37 signal-cli-rest-api  | + hostname -I
2023-11-08 18:15:37 signal-cli-rest-api  | + awk {print $1}
2023-11-08 18:15:37 signal-cli-rest-api  | + export HOST_IP=172.20.0.2
2023-11-08 18:15:37 signal-cli-rest-api  | + exec setpriv --reuid=1000 --regid=1000 --init-groups --inh-caps=-cap_0,-cap_1,-cap_2,-cap_3,-cap_4,-cap_5,-cap_6,-cap_7,-cap_8,-cap_9,-cap_10,-cap_11,-cap_12,-cap_13,-cap_14,-cap_15,-cap_16,-cap_17,-cap_18,-cap_19,-cap_20,-cap_21,-cap_22,-cap_23,-cap_24,-cap_25,-cap_26,-cap_27,-cap_28,-cap_29,-cap_30,-cap_31,-cap_32,-cap_33,-cap_34,-cap_35,-cap_36,-cap_37,-cap_38,-cap_39,-cap_40 signal-cli-rest-api -signal-cli-config=/home/.local/share/signal-cli
2023-11-08 18:15:37 signal-cli-rest-api  | time="2023-11-08T23:15:37Z" level=info msg="Started Signal Messenger REST API"
2023-11-08 18:15:37 signal-cli-rest-api  | time="2023-11-08T23:15:37Z" level=error msg="Couldn't read data for number : EOF. Is the number properly registered?"
```

**Comment by RJ-Make** [comment] 2023-11-08 23:27
> Ah found the solution here: [#340 (comment)](https://github.com/bbernhard/signal-cli-rest-api/issues/340#issuecomment-1792910871)
> 
> You have to manuelly edit the file in /signal/cli/config/data/(randomnumber) and put your number in the field username as well (was set to null). Then restart the container. Works now.

THANK YOU!! This was the cause of my issue as well.

**Comment by kamgiel** [comment] 2023-11-11 12:47
> > Ah found the solution here: [#340 (comment)](https://github.com/bbernhard/signal-cli-rest-api/issues/340#issuecomment-1792910871)
> > You have to manuelly edit the file in /signal/cli/config/data/(randomnumber) and put your number in the field username as well (was set to null). Then restart the container. Works now.
> 
> THANK YOU!! This was the cause of my issue as well.

Any way to use this solution while i'm using add-on version instead of docker?

**Comment by dan-s-github** [comment] 2023-11-12 03:30
for those running the add-on, here is how I fixed it

1. disable protected mode on ssh terminal, restart add-on
2. go to terminal
```
# connect to container
docker exec -it addon_83ec9c64_signal_messenger /bin/bash
# change current user as mentioned in login message
su signal-api
# find your <random number> account
ls -al
# check content to find username line (needed for next step)
cat <random number>
# optional create a backup of current config
cp <random number> <random number>.bak
# replace username value with value from number (line above)
sed -i 's/"username" : null/"username" : "<same value as in number>"/' <random number>
# check file again to see if modifications worked
cat <random number>
# leave container
exit 
exit
```
3. restart signal add-on
4. enable protection mode on ssh terminal, restart add-on 

Hope this helps until update comes out

**Comment by passture** [comment] 2023-11-13 09:15
Thanks for fix, @dan-s-github !

Just a minor detail regarding this:

> for those running the add-on, here is how I fixed it
> 
>     1. disable protected mode on ssh terminal, restart add-on

If you are using the "Terminal & SSH" add-on, there is no easy way to disable protection mode.  Instead, replace it with the "Advanced SSH & Web Terminal" add-on.  There is a protection mode toggle in the add-on settings.

**Comment by ThorpeJosh** [comment] 2023-11-13 22:30
@RJ-Make I also encountered this issue upgrading from `0.69` to `0.70`
Version `0.70` is changing the `jsonrpc2.yml` as soon as it boots. I restored my config and downgraded to `0.69` and everything works again.

Restoring my working config on `0.70` doesn't work, it immediately screws it up again.

**Comment by RJ-Make** [comment] 2023-11-14 02:46
> @RJ-Make I also encountered this issue upgrading from `0.69` to `0.70`
> Version `0.70` is changing the `jsonrpc2.yml` as soon as it boots. I restored my config and downgraded to `0.69` and everything works again.
> 
> Restoring my working config on `0.70` doesn't work, it immediately screws it up again.

Don't restore the file, edit it and make the change listed in the referenced discussion. That should get you fixed up on .70

**Comment by dan-s-github** [comment] 2023-11-14 06:48
> @RJ-Make I also encountered this issue upgrading from `0.69` to `0.70` Version `0.70` is changing the `jsonrpc2.yml` as soon as it boots. I restored my config and downgraded to `0.69` and everything works again.
> 
> Restoring my working config on `0.70` doesn't work, it immediately screws it up again.

Configuration file version is different between 0.70 and 0.69 as you can see [here](https://github.com/bbernhard/signal-cli-rest-api/issues/340#issuecomment-1793502041)

**Comment by ThorpeJosh** [comment] 2023-11-14 19:53
Thanks for tips. I originally updated to `0.70` on the day of release and so rolling back was much easier than playing around with configs. I have manually fixed it now as per the multiple open issues on this.

Great project. I am thankful to all the contributors of all the open source projects I utilize. It is sad to see this latest release still breaking all the json-rpc users setups for 3 weeks now. A patch could have been released by now to avoid further breakages. Project has been very reliable till this point, however I'll be more tentative to update in future.

**Comment by bbernhard** [comment] 2023-11-14 20:47
> Thanks for tips. I originally updated to `0.70` on the day of release and so rolling back was much easier than playing around with configs. I have manually fixed it now as per the multiple open issues on this.
> 
> Great project. I am thankful to all the contributors of all the open source projects I utilize. It is sad to see this latest release still breaking all the json-rpc users setups for 3 weeks now. A patch could have been released by now to avoid further breakages. Project has been very reliable till this point, however I'll be more tentative to update in future.

What makes me sad as an open source contributor is to read posts like this. Yes, the latest release broke some setups. Am I happy with it? Definitely not. Did I try to test the release upfront as thoroughly as possible? I think so. 

But there are so many different combinations of setups out that there, that it makes it really hard to ensure that a release is working as intended and there are no regressions. There are the different modes (normal, native, json-rpc), different architectures (armv7, arm64, amd64), different signal-cli configs (some of them were created recently, some of them were migrated often), some people use linked devices, others one (or more) dedicated phone numbers, etc. Testing all those combinations upfront is a lot of work and sometimes even exceeds the time that I can put into maintaining this project in my free time.

Should I've released an emergency patch after people reported the issue? Maybe. But as the json-rpc mode is currently heavily reworked and this issue can be fixed by changing the config, I decided against it. Believe me, I am not happy either that the json-rpc mode is broken for some users.

There will be a new pre-release soon, which contains the reworked json-rpc mode. Instead of spawning a signal-cli process for each registered number in json-rpc mode, only one signal-cli process will be spawned (and the signal-cli multi-account mode will be used). This should reduce the resources of the docker container significantly. However, as this is quite a big change, there is of course potential for regression and bugs. I would be really grateful, if a lot of people could give this pre-release a try and help with testing.

**Comment by Kariton** [comment] 2023-11-15 11:02
Hey Folks,

I discovered now the second time that my `"username"` field was wrong.

> https://github.com/bbernhard/signal-cli-rest-api/issues/440#issuecomment-1812250315
> I found out what does mess with the "username": field!
> 
> i linked a new device to my account afterwards.
>
> what i did:
> 
> - signal on smartphone
> - singla-cli-rest-api linked (native mode)
> - fixed the username issue (which then is null)
> - singla-cli-rest-api (jsonRPC)
> - linked my desktop to signal
> - fixed the username issue (which then is "")

can someone try / confirm this?
does the value of `"username":` change when linking another new device after linking (and using) signal-cli-rest-api?

**Comment by bbernhard** [comment] 2023-11-16 20:37
As already mentioned above, the json-rpc mode has been reworked and now there is also a docker image available for testing. If you want to give it a try, please use the following docker image tag: `bbernhard/signal-cli-rest-api:0.131-dev`. As the changes were quite big, **please except that this image may contain some bugs**. But in order to get a proper release done, I definitely need your help in testing the image. Thank you!

edit: This release now also supports linking devices in json-rpc mode. So it is not necessary anymore to switch to the normal/native mode in order to link your device.

**Comment by Kariton** [comment] 2023-11-17 01:17
@bbernhard, thanks for the work you and passion you put in this project. 
the reduced system utilization is impressive!

![image](https://github.com/bbernhard/signal-cli-rest-api/assets/67470612/95e0eb27-4c08-47ec-89e9-d17fa51330ad)
> Container Versions: Orange: v0.70, Blue: 0.131-dev, Pink-isch: 0.131-dev
I restarted 0.131 once because i might have encountered a bug.

I have one instance and use it for 2 linked numbers and 3 directly registered ones.

The bug i was talking about: 
I use [signalbot](https://pypi.org/project/signalbot/) and spawn for each number a separate thread.
This used to work with the old version. (v0.70)
Not sure how familiar you are with this python module but it establishes an websocket to fetch new meessages.
So there are 4 open connections (one number unused)

I send a message to each number quickly one after another and sometimes only one respond and other times another does.

**Comment by bbernhard** [comment] 2023-11-17 03:20
> @bbernhard, thanks for the work you and passion you put in this project. the reduced system utilization is impressive!
> 
> ![image](https://user-images.githubusercontent.com/67470612/283636894-95e0eb27-4c08-47ec-89e9-d17fa51330ad.png)
> 
> > Container Versions: Orange: v0.70, Blue: 0.131-dev, Pink-isch: 0.131-dev
> > I restarted 0.131 once because i might have encountered a bug.
> 
> I have one instance and use it for 2 linked numbers and 3 directly registered ones.
> 
> The bug i was talking about: I use [signalbot](https://pypi.org/project/signalbot/) and spawn for each number a separate thread. This used to work with the old version. (v0.70 - jsonRPC) Not sure how familiar you are with this python module but it establishes an websocket to fetch new messages. So there are 4 open connections (one number unused).
> 
> I send a message to each number quickly one after another and only one responses and other times another does.
> 
> Is it worth creating an separate issue or is this info sufficient? :)

Thank you very much for testing and providing this feedback. Tests with such big setups are really valuable and greatly appreciated! Regarding the issue: A dedicated issue would be great, as this makes it easier for tracking. Do you know if it is related to the speed you are sending those messages? Currently trying to figutre out whether it is somehow timing related or a general issue.

**Comment by Kariton** [comment] 2023-11-17 05:46
other (somewhat) related issues found:
https://github.com/bbernhard/signal-cli-rest-api/issues/233
https://github.com/bbernhard/signal-cli-rest-api/issues/419

maybe it is now, with the jsonRPC rework, an actual problem?

**Comment by jarrah31** [comment] 2023-11-21 19:13
@bbernhard I am happy to test the dev release too - has there been any updated versions since `bbernhard/signal-cli-rest-api:0.131-dev`? Where is the best place to monitor new releases for testing please?

I originally fixed the same problem by adding my number to the username field, but things broke again after I re-linked a new desktop client to my main number. Unlike @Kariton my username field still has my number so there's nothing more I can do other than test the new dev build. (my container is running at 100% as well)

I also really appreciate the time and effort you put into this project. My Home Assistant notifications wouldn't be the same without it! :)

**Comment by bbernhard** [comment] 2023-11-22 19:28
> @bbernhard I am happy to test the dev release too - has there been any updated versions since `bbernhard/signal-cli-rest-api:0.131-dev`? Where is the best place to monitor new releases for testing please?
> 
> I originally fixed the same problem by adding my number to the username field, but things broke again after I re-linked a new desktop client to my main number. Unlike @Kariton my username field still has my number so there's nothing more I can do other than test the new dev build. (my container is running at 100% as well)
> 
> I also really appreciate the time and effort you put into this project. My Home Assistant notifications wouldn't be the same without it! :)

Thanks for the kind words!

Yes, the version is still the latest. You can use `bbernhard/signal-cli-rest-api:latest-dev`, which always points to the latest dev version, but I wouldn't recommend that, as I sometimes push versions which aren't fully functional yet. If a version contains bigger changes (like the next version) and I need help in testing, I usually announce that either in the github issues or the github discussions. I also often release pre-releases - in order to get a notification when a new pre-release is out, please watch this repository and enable notifications for releases (see https://stackoverflow.com/a/49350626 on how to do that)

**Comment by bbernhard** [comment] 2023-11-22 19:55
see also: https://github.com/bbernhard/signal-cli-rest-api/discussions/454

**Comment by markmghali** [comment] 2023-11-28 15:44
moved to the 0.131-dev build and that fixed my issues right away! using unraid server OS. json-rpc.

Thank you again

**Comment by bbernhard** [comment] 2023-12-20 20:48
should be fixed with the latest version

**Closed by bbernhard** 2023-12-20 20:48 UTC

**Comment by ThorpeJosh** [comment] 2024-01-09 13:58
> @bbernhard, thanks for the work you and passion you put in this project. the reduced system utilization is impressive!
> 
> ![image](https://private-user-images.githubusercontent.com/67470612/283636894-95e0eb27-4c08-47ec-89e9-d17fa51330ad.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4MDg0OTgsIm5iZiI6MTcwNDgwODE5OCwicGF0aCI6Ii82NzQ3MDYxMi8yODM2MzY4OTQtOTVlMGViMjctNGMwOC00N2VjLTg5ZTktZDE3ZmE1MTMzMGFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA5VDEzNDk1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgxMmE2ZjVhZmNlMGZjYTZkODE4MTI4NDZjYjRjZTM2YzQxZjQyNTVjYjU0ZjQxYTIzY2FhNTc1OGMzYTliZDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YG8ifmcMj-iD6vehIpWXhGhZFEK4oAH8fqfQWfz54e8)
> 
> > Container Versions: Orange: v0.70, Blue: 0.131-dev, Pink-isch: 0.131-dev
> > I restarted 0.131 once because i might have encountered a bug.
> 
> I have one instance and use it for 2 linked numbers and 3 directly registered ones.
> 
> The bug i was talking about: I use [signalbot](https://pypi.org/project/signalbot/) and spawn for each number a separate thread. This used to work with the old version. (v0.70 - jsonRPC) Not sure how familiar you are with this python module but it establishes an websocket to fetch new messages. So there are 4 open connections (one number unused).
> 
> I send a message to each number quickly one after another and only one responses and other times another does.
> 
> Is it worth creating an separate issue or is this info sufficient? :)

Hi @Kariton. I am wandering if you are seeing the reduced memory usage on the latest release 0.80?
I just updated and my memory usage for the signal-cli-rest-api container increased from 230MB to 300MB. I also use it with signalbot. Cheers
