### ISSUE TITLE
Native mode is not working anymore since an update

### ISSUE THREAD

**Issue by f45tb00t** [bbernhard/signal-cli-rest-api#158] opened 2021-09-03 14:48 UTC
### The problem

Hello,

I cannot tell exactly with which update from you it came, but unfortunately the native mode is not working on my system anymore. 
Before it took 2-3 seconds for message delivery. Now its up to 12+ seconds for the delivery. So by now it makes no difference if native is 0 or 1.

Is it somehow possible to get the old behavior back?

Cheers

fb

### Are you using the latest released version?

- [X] Yes

### Have you read the troubleshooting page?

- [X] Yes

### What type of installation are you running?

signal-cli-rest-api Docker Container

### In which mode are you using the docker container?

Native Mode

### What's the architecture of your host system?

x86-64

**Comment by bbernhard** [comment] 2021-09-07 17:33
I haven't seen any performance issues with x86-64, but I've seen some performance degradation on armv7. Not sure if that's the same root cause, but I've tracked the issues with armv7 down to [Version 0.42](https://github.com/bbernhard/signal-cli-rest-api/releases/tag/0.41). In that release signal-cli updated to libsignal-client version 0.8.1 and I _think_ this version is responsible for the performance degradation (at least on armv7).

I thought about opening a ticket in the libsignal-client bug tracker, but the README explicitly states that the use of this library out of Signal is unsupported. And as signal-cli is a community project and not a officially supported client, I guess we are out of luck. (And even if libsignal-client would address bug reports from the community, then we would first need to prove to them that it's actually libsignal-client that is causing the performance degradation - which I haven't done. But as the library contains some crypto stuff, I think it's likely that libsignal-client is responsible for that).

If your system has a normal system load and plenty of free RAM, I think your best bet is probably to downgrade the docker container to the version that worked for you. 

With the next signal-cli version, a new API (JSON RPC) will be released. (see https://github.com/AsamK/signal-cli/discussions/679 for details). I already had a quick look at it and it feels pretty snappy and powerful. I think this API could speed up things quite a bit (and maybe even make the native mode obsolete).

**Comment by andreasbrett** [comment] 2021-09-10 09:20
This new JSON RPC feature looks promising! Can't wait to see it in action.

**Comment by andreasbrett** [comment] 2021-09-13 07:16
Oooh, it's there already! https://github.com/AsamK/signal-cli/releases/tag/v0.9.0

**Comment by bbernhard** [comment] 2021-09-13 20:12
I think I have a first version ready. Is there anyone who wants to help with testing? (word of caution: I've changed _a lot_ of code..so it's likely that the test version will contain some bugs and issues)

**Comment by andreasbrett** [comment] 2021-09-13 20:15
Sure, I'd be glad to help with testing. Let me know what I can do.

**Comment by bbernhard** [comment] 2021-09-14 16:00
> Sure, I'd be glad to help with testing. Let me know what I can do.

Many thanks! I've started a discussion here: https://github.com/bbernhard/signal-cli-rest-api/discussions/160

**Comment by f45tb00t** [comment] 2021-09-22 09:23
Hello Bernhard,

sorry for the late reply. 
I don't think its signal itself. Due to my testes and measurements I could see that the send and receive is done very quickly. 
For example: Send 14:09:51 and Received: 14:09:52. So the processing with the signal-cli takes a lot of longer than before with an older version. unfortunately the rollback to an older version is still not good I guess, because of missing details.
Or did you fix this already?

**Comment by andreasbrett** [comment] 2021-09-22 10:19
> Hello Bernhard,
> 
> sorry for the late reply.
> I don't think its signal itself. Due to my tests and measurements I could see that the send and receive is done very quickly.
> For example: Send 14:09:51 and Received: 14:09:52. So the processing with the signal-cli takes a lot of longer than before with an older version. unfortunately the rollback to an older version is still not good I guess, because of missing details.
> Or did you fix this already?

Check the new JSONRPC-API feature linked in the discussion above. For my setup it's faster than native mode because signal-cli is lurking in the background waiting to send/receive messages.

**Comment by f45tb00t** [comment] 2021-09-22 10:35
That's pretty much awesome. 1 second from sending to delivery. 
If anyone wanna test this. Remove the old native and " AUTO_RECEIVE_SCHEDULE=0 22 * * *" as well. Otherwise the container did not came up for me

**Closed** 2022-01-01 11:03 UTC
