### ISSUE TITLE
Version 0.30 is not working

### ISSUE THREAD

**Issue by gadric** [bbernhard/signal-cli-rest-api#46] opened 2021-01-05 12:21 UTC
I have upgrade to the latest version and now it is not working anymore. 

The log files show the following error: 

```
+ set -e
+ chown 1000:1000 -R /home/.local/share/signal-cli
+ cat
+ exec setpriv --reuid=1000 --regid=1000 --init-groups --inh-caps=-all signal-cli-rest-api
setpriv: libcap-ng is too old for "all" caps
```

**Comment by bbernhard** [comment] 2021-01-05 12:32
Oh damn, that's related to https://github.com/bbernhard/signal-cli-rest-api/issues/31 :/

Which host platform are you using? I've tried it on x86-64 and armv7 and haven't noticed any problems.

**Comment by gadric** [comment] 2021-01-05 12:35
x86-64 IntelNUC

**Comment by bbernhard** [comment] 2021-01-05 12:37
> x86-64 IntelNUC

Thanks. Just looked it up and it looks like it could be related to the kernel version of the host system. Which kernel do you use?

**Comment by gadric** [comment] 2021-01-05 12:47
No problem. Dont worry. let me know when I can test :D

**Comment by haberda** [comment] 2021-01-05 15:45
Hey @bbernhard I am having the same issue with the HassIO add-on. Looking back at what I ran when I tested it, it looks like I messed up and copied and launched the wrong Dockerfile, so I did't actually test the dev container. Sorry about that. For now I will roll back the add-on. Thanks!

**Comment by bbernhard** [comment] 2021-01-05 15:50
> Hey @bbernhard I am having the same issue with the HassIO add-on. Looking back at what I ran when I tested it, it looks like I messed up and copied and launched the wrong Dockerfile, so I did't actually test the dev container. Sorry about that. For now I will roll back the add-on. Thanks!

Just out of interest: What's the architecture/kernel version of your host system? (hoping to find some similarities to the system @gadric uses)

**Comment by bbernhard** [comment] 2021-01-05 16:43
> My main system is x86 Debian 10 stable with kernel 5.9.0-0.bpo.2-amd64 similar to @gadric. Just for reference, I just tested version 0.30 on a Raspberry Pi (for sure the right version this time!) with Home Assistant OS 5.9, the add-on works fine on that architecture/kernel.

Cool, thanks! That narrows it down a bit. So hopefully with a 5.9 kernel I should be able to reproduce the issue. 🤞

**Comment by bbernhard** [comment] 2021-01-08 17:41
@gadric @haberda I think the issue should be fixed with now. In case you want to give it a try, please use this image here: `bbernhard/signal-cli-rest-api:latest-dev` (Don't forget to switch back to the `latest` tag after testing, as the `latest-dev` is mainly used for testing and often contains images that are not yet fully working). If everything works for you, I'll update the `latest` tag :)

**Comment by gadric** [comment] 2021-01-08 17:45
@bbernhard: Thanks for the fix. Jus tested. It works. My messages were sent.

**Comment by bbernhard** [comment] 2021-01-08 18:17
Thanks a lot for testing! The docker build is now running...it usually takes about ~2hrs to build + upload an image for all architectures. I'll let you know as soon as it is finished.

**Comment by haberda** [comment] 2021-01-08 18:57
In order for this to work for the hass-io add-on I will have to change the ownership of the state file. Using:

`chown 1000:1000 -R /data/data`

works when I do it manually after ssh-ing into the container. I can dissect the container to find where best to inject that command during initialization, but if you know the best place to do it, it would save me some time.

Once the ownership changes it works fine. Thanks again!

**Comment by haberda** [comment] 2021-01-08 19:08
Never mind, It was easy to figure out!

**Comment by haberda** [comment] 2021-01-08 19:53
One last issue that I ran into, changing ownership of the state file does not appear to be enough. My old state file had permissions set to 600. Doing:
`chmod 660 state_file_location`
fixes it.

Can we add a chmod line to the entrypoint file on your next release? I assume that going forward newly generated state files will come with permissions set to 660 so this is just a backward compatibility thing. I can always inject the line myself for the add-on if you don't think it's necessary.

**Comment by bbernhard** [comment] 2021-01-08 20:19
Ok, the `latest` tag should now updated :)

> One last issue that I ran into, changing ownership of the state file does not appear to be enough.

What do you mean exactly by state file? Do you mean the "+xxxx" file inside the `data` directory where `signal-cli` stores its config?

If so, then I am struggling a bit to understand why this is necessary in your case. Afaik the only difference between between `600` and `660` is, that with the former only the owner of the file can read/write the file whereas with the latter the owner and group members can read/write the file. But with `chown 1000:1000 -R /data/data` everything inside the `data/data` directory should have it's owner changed. So even if the file has permission `600` it should work, no? :thinking: 

Unfortunately, I can't reproduce the issue here on my system (I am not using the HA addon though). Maybe the HA addon behaves somehow different here?

**Comment by gadric** [comment] 2021-01-08 21:53
Updated to the `latest` version. Works! Perfect! Thank you a lot

**Comment by haberda** [comment] 2021-01-08 23:35
> Ok, the `latest` tag should now updated :)
> 
> > One last issue that I ran into, changing ownership of the state file does not appear to be enough.
> 
> What do you mean exactly by state file? Do you mean the "+xxxx" file inside the `data` directory where `signal-cli` stores its config?
> 
> If so, then I am struggling a bit to understand why this is necessary in your case. Afaik the only difference between between `600` and `660` is, that with the former only the owner of the file can read/write the file whereas with the latter the owner and group members can read/write the file. But with `chown 1000:1000 -R /data/data` everything inside the `data/data` directory should have it's owner changed. So even if the file has permission `600` it should work, no? thinking
> 
> Unfortunately, I can't reproduce the issue here on my system (I am not using the HA addon though). Maybe the HA addon behaves somehow different here?

Yeah, I don't really understand it, and I do mean the +xxxx file. I tried several iterations cloning the file from my production instance each time. The only combo that worked was the chown that is in your entry point file (pointing insted to /data/data) and then changing permission to 660. The default permission had been 600. When the permission is 600 the container log shows that the rest api was queried but no message is sent. No error though. As soon as I go to 660 the messages send again.

I will inject the chmod into the entrypoint in the add-on, it can't hurt anyway.

The HA addon is not much different from your container. All I do is redirect the storage location of the state file and expose /data as a volume.

**Comment by bbernhard** [comment] 2021-01-09 21:32
> I will inject the chmod into the entrypoint in the add-on, it can't hurt anyway.

Perfect, thanks! 

I am currently busy with other stuff, but as soon as I have a minute to spare I'll give your HA addon a try. Maybe it's possible to reproduce the issue that way :)

**Comment by haberda** [comment] 2021-01-09 23:34
The repository is still pointing to the 0.25 container. I may get around to updating it tomorrow. So, don't rush to test.

**Comment by haberda** [comment] 2021-01-10 02:17
Add-on is now up to date with version 31. I think my file permissions problems were actually spotty DNS issues rather than actual file permissions. So the add-on was working fine, it's just that sometimes my DNS would not be working so the message would not send. I found an issue with my Adguard instance that was causing large latency sometimes. I think it was just timing out. When I bypass and use public DNS the file permission issue evaporates.

**Comment by bbernhard** [comment] 2021-01-14 14:34
> Add-on is now up to date with version 31. I think my file permissions problems were actually spotty DNS issues rather than actual file permissions. So the add-on was working fine, it's just that sometimes my DNS would not be working so the message would not send. I found an issue with my Adguard instance that was causing large latency sometimes. I think it was just timing out. When I bypass and use public DNS the file permission issue evaporates.

Ah, perfect. In this case, I'll close the issue. Thanks a lot! :)

**Closed by bbernhard** 2021-01-14 14:34 UTC
