### ISSUE TITLE
Link device in JSON-RPC mode

### ISSUE THREAD

**Issue by kxait** [bbernhard/signal-cli-rest-api#433] opened 2023-10-29 16:09 UTC
### Feature Request

Hi, there was an update to signal-cli regarding linking devices in JSON-RPC mode, it would be really nice to have this support in this project, as for e.g. my application I need to be able to link devices on the fly.

Issue: https://github.com/AsamK/signal-cli/issues/1319
Commit: https://github.com/AsamK/signal-cli/commit/a7a5947a1bc468cbf202c603ed14fe40b14c73b0

It requires the json-rpc client to be connected without a `-u` parameter (in multi-account mode), and for there to be 2 requests sent (`startLink` which gets the QR code and `finishLink` which waits for the device to be registered). It seems this would require big changes in the way we handle the JSON-RPC connections

1. Do not assume every json-rpc connection needs a phone number associated with it
2. Add a multi-account mkfifo to signal-cli
   - do not crash if we didn't find any registered numbers at the beginning?
3. Send a request **after** we return the QR code and wait for it to finish or wait for a timeout
4. Regenerate the `jsonrpc2.yml` config after the linking is finished and reload it

So far, I have got it to actually link the number in the background and add it to `data/`, but I think actually reloading `jsonrpc2.yml` would require some big changes and assistance/guidance from @bbernhard (let me know if I'm on the right path)

My branch: https://github.com/bbernhard/signal-cli-rest-api/commit/c7f22838904b7ea33d539dfcbce4a20d0fea0020

```
[GIN] 2023/10/29 - 10:47:31 | 200 |  1.531793584s |      172.17.0.1 | GET      "/v1/qrcodelink?device_name=test"
2023/10/29 10:47:46 Linking device result: {"number":"+48123456789"}
```

**Comment by bbernhard** [comment] 2023-10-29 16:24
Hi,

I haven't had time to look at your changes (will do that in the next days), but just wanted to let you know that I am  working on implementing the register command in json-rpc mode. Therefore I had to change a bit in the jsonrpc2.yml generation. I hope to get that done in the next days. That should make it then easier to implement the linking functionality :)

**Comment by kxait** [comment] 2023-10-29 16:29
Cool! I'll then wait until you finish the jsonrpc2.yml generation before moving on with this, unless you want to do the linking functionality aswell.

**Comment by bbernhard** [comment] 2023-10-29 16:33
> Cool! I'll then wait until you finish the jsonrpc2.yml generation before moving on with this, unless you want to do the linking functionality aswell.

I would really appreciate your help with the linking functionality! I personally do not use linked devices, so any help there is greatly appreciated! :)

**Comment by bbernhard** [comment] 2023-10-29 20:14
Ok, unfortunately it is not as straightforward as I hoped it to be. The problem is, that when we establish a connection to the jsonRpc interface without a number (aka "multi account mode"), the signal-cli instance locks the whole signal-cli config file. That means we cannot spawn multiple signal-cli jsonRpc instances anymore, as the first signal-cli process would acquire the lock and all the other instances would wait forever for the file lock (one can see this line in the logs:  `INFO  SignalAccount - Config file is in use by another instance, waiting…`). So I guess we need to change the whole concept of the json-rpc mode to make that work. 

Instead of spawning multiple account specific signal-cli processes, we need to spawn just one signal-cli process in the multi-account mode. For sending data that should be pretty straightforward. But receiving the data and delegating the correct data to the right websocket channel will be a challenge, as we now need to parse the received data, check the account it is meant to be for and write it to the correct websocket channel.

**Comment by kxait** [comment] 2023-10-29 23:11
yes, but doesn't this eliminate the need for `jsonrpc2.yml` and the whole complexity that comes with it? we then just need one mkfifo for sending and receiving and we can rely on `mc-signal` to handle account logic while we take care of linking devices and checking if the phone number a REST command is associated with is registered on the go. it does sound like a daunting task, though

**Comment by bbernhard** [comment] 2023-10-30 19:20
A first version should be implemented now. Maybe I'll simplify the code even further in the future, but I think it should be good to go for now. If you want to have a look, the changes are already merged to the master branch :)

**Comment by kxait** [comment] 2023-11-01 10:39
hey, just had a look at your changes. it seems that `receiveChannel` will fire for **every** incoming message, regardless of phone number. if we have 50 receivers, the case on `src/api/api.go:399` will fire 50 times, and only go through once. this could lead to a lot of redundancy at scale, I think it would be better to have 1 `receiveChannel` for every receiver, and unmarshal the JSON to get Account inside of `ReceiveData`, do the filtering there and only fire the correct receiver chan (if found). let me know what you think, and if you'd be willing to make this change (I can create the PR otherwise).

That said, I'm going to get started on the linking functionality, it shouldn't be in the way of the above. Thanks!

**Comment by bbernhard** [comment] 2023-11-01 10:49
> hey, just had a look at your changes. it seems that `receiveChannel` will fire for **every** incoming message, regardless of phone number. if we have 50 receivers, the case on `src/api/api.go:399` will fire 50 times, and only go through once. this could lead to a lot of redundancy at scale, I think it would be better to have 1 `receiveChannel` for every receiver, and unmarshal the JSON to get Account inside of `ReceiveData`, do the filtering there and only fire the correct receiver chan (if found). let me know what you think, and if you'd be willing to make this change (I can create the PR otherwise).
> 
> That said, I'm going to get started on the linking functionality, it shouldn't be in the way of the above. Thanks!

You are totally right, that's definitely something to improve. I mainly did it that way, because I was a bit short on time and wanted to get a first version done, so that you can have a look at the linking device functionality (and don't have to wait for ages to get started).

If you want to implement the improvements, please feel free to so. I am a bit short on time the next few days/the next week, so I probably won't have much time to look into this. :)

**Comment by kxait** [comment] 2023-11-11 13:37
I finished the implementation in #445
I tested the flow + receiving messages, creating/deleting groups, so it seems to work
I had to change the message response functionality a bit, tell me if it's ok

**Closed** 2023-11-13 17:01 UTC
