### ISSUE TITLE
No serializer found for class org.asamk.signal.json.JsonSyncMessage and no properties discovered to create BeanSerializer

### ISSUE THREAD

**Issue by gf78** [bbernhard/signal-cli-rest-api#103] opened 2021-03-07 09:45 UTC
On /receive

{
error: "WARN ReceiveCommand - "--json" option has been deprecated, please use the global "--output=json" instead. Failed to send/receive message (Assertion): com.fasterxml.jackson.databind.exc.InvalidDefinitionException: No serializer found for class org.asamk.signal.json.JsonGroupInfo and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS) (through reference chain: java.util.HashMap["envelope"]->org.asamk.signal.json.JsonMessageEnvelope["dataMessage"]->org.asamk.signal.json.JsonDataMessage["groupInfo"]) java.lang.AssertionError: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: No serializer found for class org.asamk.signal.json.JsonGroupInfo and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS) (through reference chain: java.util.HashMap["envelope"]->org.asamk.signal.json.JsonMessageEnvelope["dataMessage"]->org.asamk.signal.json.JsonDataMessage["groupInfo"]) at org.asamk.signal.JsonWriter.write(JsonWriter.java:32) at org.asamk.signal.JsonReceiveMessageHandler.handleMessage(JsonReceiveMessageHandler.java:37) at org.asamk.signal.manager.Manager.receiveMessages(Manager.java:1782) at org.asamk.signal.commands.ReceiveCommand.handleCommand(ReceiveCommand.java:168) at org.asamk.signal.App.handleLocalCommand(App.java:211) at org.asamk.signal.App.init(App.java:169) at org.asamk.signal.Main.main(Main.java:43) Caused by: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: No serializer found for class org.asamk.signal.json.JsonGroupInfo and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS) (through reference chain: java.util.HashMap["envelope"]->org.asamk.signal.json.JsonMessageEnvelope["dataMessage"]->org.asamk.signal.json.JsonDataMessage["groupInfo"]) at com.fasterxml.jackson.databind.SerializerProvider.reportBadDefinition(SerializerProvider.java:1191) at com.fasterxml.jackson.databind.DatabindContext.reportBadDefinition(DatabindContext.java:313) at com.fasterxml.jackson.databind.ser.impl.UnknownSerializer.failForEmpty(UnknownSerializer.java:71) at com.fasterxml.jackson.databind.ser.impl.UnknownSerializer.serialize(UnknownSerializer.java:33) at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:727) at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:719) at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:155) at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:727) at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:719) at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:155) at com.fasterxml.jackson.databind.ser.std.MapSerializer.serializeFields(MapSerializer.java:722) at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:643) at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:33) at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:480) at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:319) at com.fasterxml.jackson.databind.ObjectMapper._configAndWriteValue(ObjectMapper.java:3906) at com.fasterxml.jackson.databind.ObjectMapper.writeValue(ObjectMapper.java:3202) at org.asamk.signal.JsonWriter.write(JsonWriter.java:29) ... 6 more If you use an Oracle JRE please check if you have unlimited strength crypto enabled, see README "
}

**Comment by bbernhard** [comment] 2021-03-07 11:59
What's your host architecture? Are you using the native mode?

**Comment by stack74** [comment] 2021-03-12 08:32
Hi, could reproduced it too but with another error message:
General 64Bit machine in native mode. Happens when try to receive a message, which could not be properly decrypted (session error). When running the signal-cli receive command directly in the container, the receive process keeps running:
signal-cli-native reports this:

Exception in thread "main" java.lang.NoClassDefFoundError: Lorg/whispersystems/libsignal/UntrustedIdentityException;
        at com.oracle.svm.jni.functions.JNIFunctions.FindClass(JNIFunctions.java:325)
        at org.signal.client.internal.Native.SessionCipher_DecryptPreKeySignalMessage(Native.java)
        at org.whispersystems.libsignal.SessionCipher.decrypt(SessionCipher.java:100)
        at org.signal.libsignal.metadata.SealedSessionCipher.decrypt(SealedSessionCipher.java:125)
        at org.signal.libsignal.metadata.SealedSessionCipher.decrypt(SealedSessionCipher.java:90)
        at org.whispersystems.signalservice.api.crypto.SignalServiceCipher.decrypt(SignalServiceCipher.java:190)
        at org.whispersystems.signalservice.api.crypto.SignalServiceCipher.decrypt(SignalServiceCipher.java:138)
        at org.asamk.signal.manager.Manager.decryptMessage(Manager.java:1432)
        at org.asamk.signal.manager.Manager.retryFailedReceivedMessage(Manager.java:1675)
        at org.asamk.signal.manager.Manager.retryFailedReceivedMessages(Manager.java:1661)
        at org.asamk.signal.manager.Manager.receiveMessages(Manager.java:1704)
        at org.asamk.signal.commands.ReceiveCommand.handleCommand(ReceiveCommand.java:168)
        at org.asamk.signal.App.handleLocalCommand(App.java:211)
        at org.asamk.signal.App.init(App.java:169)
        at org.asamk.signal.Main.main(Main.java:43)

And aborts.

**Comment by filipre** [comment] 2021-03-12 23:42
Got this error as well with `USE_NATIVE=1` on my MacBook Pro 10.15.4. When switching to `USE_NATIVE=0` it seems to work, but this is very slow. Both native and not appear to use `signal-cli 0.8.0` but native must have some error somewhere? Does someone have an idea how we could solve this issue?

**Comment by bbernhard** [comment] 2021-03-13 11:37
Which host architecture are you using? In case of ARM64, it could be related to this: https://github.com/bbernhard/signal-cli-rest-api/issues/99

**Comment by filipre** [comment] 2021-03-13 12:02
```
Darwin Renes-MBP.fritz.box 19.4.0 Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64 x86_64
```

I don't think it's related to #99 because I did not get the error from this issue and our issue here mentions 
>"--json" option has been deprecated, please use the global "--output=json" instead.

which indicates a programming error or something. It does not look like a GraalVM error, does it? Or maybe GraalVM did not convert (?) the code correctly and thus introduced the JSON error?

**Comment by bbernhard** [comment] 2021-03-13 12:53
That's odd. For me receiving messages in the native mode works with x86-64. 

> which indicates a programming error or something.

To me it looks like that it's just a warning log. Of course, it will be changed with the next release, but the command should still work that way, see also: https://github.com/AsamK/signal-cli/blob/master/src/main/java/org/asamk/signal/commands/ReceiveCommand.java#L61

edit: Have a look here: https://github.com/AsamK/signal-cli/issues/17. Are you maybe trying to decrypt messages from clients with untrusted identities?

**Comment by filipre** [comment] 2021-03-13 13:22
No, it must be an error. I was referring to the part after the warning, sorry:
```
Failed to send/receive message (Assertion): com.fasterxml.jackson.databind.exc.InvalidDefinitionException: No serializer found for class org.asamk.signal.json.JsonSyncMessage and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS) (through reference chain: java.util.HashMap["envelope"]->org.asamk.signal.json.JsonMessageEnvelope["syncMessage"])
java.lang.AssertionError: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: No serializer found for class org.asamk.signal.json.JsonSyncMessage and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS) (through reference chain: java.util.HashMap["envelope"]->org.asamk.signal.json.JsonMessageEnvelope["syncMessage"])
	at org.asamk.signal.JsonWriter.write(JsonWriter.java:32)
	at org.asamk.signal.JsonReceiveMessageHandler.handleMessage(JsonReceiveMessageHandler.java:37)
	at org.asamk.signal.manager.Manager.receiveMessages(Manager.java:1782)
	at org.asamk.signal.commands.ReceiveCommand.handleCommand(ReceiveCommand.java:168)
	at org.asamk.signal.App.handleLocalCommand(App.java:211)
	at org.asamk.signal.App.init(App.java:169)
	at org.asamk.signal.Main.main(Main.java:43)
Caused by: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: No serializer found for class org.asamk.signal.json.JsonSyncMessage and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS) (through reference chain: java.util.HashMap["envelope"]->org.asamk.signal.json.JsonMessageEnvelope["syncMessage"])
	at com.fasterxml.jackson.databind.SerializerProvider.reportBadDefinition(SerializerProvider.java:1191)
	at com.fasterxml.jackson.databind.DatabindContext.reportBadDefinition(DatabindContext.java:313)
	at com.fasterxml.jackson.databind.ser.impl.UnknownSerializer.failForEmpty(UnknownSerializer.java:71)
	at com.fasterxml.jackson.databind.ser.impl.UnknownSerializer.serialize(UnknownSerializer.java:33)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:727)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:719)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:155)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serializeFields(MapSerializer.java:722)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:643)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:33)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:480)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:319)
	at com.fasterxml.jackson.databind.ObjectMapper._configAndWriteValue(ObjectMapper.java:3906)
	at com.fasterxml.jackson.databind.ObjectMapper.writeValue(ObjectMapper.java:3202)
	at org.asamk.signal.JsonWriter.write(JsonWriter.java:29)
	... 6 more
If you use an Oracle JRE please check if you have unlimited strength crypto enabled, see README
```

it only happens for me when the response array is not empty, i.e. when I receive a new message. That means receiving messages work until the serialization part for the JSON response. That makes sense because the program probably knows how to serialize the empty array but not the complicated message envelope. I just don't fully understand why the serializer is defined when `USE_NATIVE=0` but not when `USE_NATIVE=1`. Do you know how we can check whether this is related to `signal-cli-rest-api` or `signal-cli`? If it is the latter, I will _bug_ them.

I don't think it is related to AsamK/signal-cli#17 either because everything works when `USE_NATIVE=0` so it's unrelated to identities.

**Comment by filipre** [comment] 2021-03-13 13:37
I found this issue https://github.com/micronaut-projects/micronaut-aws/issues/207#issuecomment-678092993 and they seem to have the same problem with GraalVM. [JsonSyncMessage](https://github.com/micronaut-projects/micronaut-aws/issues/207#issuecomment-678092993) does not have any / correct annotations so GraalVM does not know which serializer to choose? But I am surprised that it works for you @bbernhard because I would expect that you can't receive *new* messages as well.

**Comment by bbernhard** [comment] 2021-03-13 14:19
Looks like there are two different issues here. The error @stack74 is experiencing is different than yours. The former looks like it could be related to the issue I've linked above.

Not sure what's causing your error and why it is working on my machine. The only thing I can think of is the host system. I do not use a Macbook.

**Comment by bbernhard** [comment] 2021-03-13 14:25
I could upload a docker image with the `dev` tag later today which bumps signal-cli to version 0.8.1. Maybe the error is already fixed there. But as I haven't seen anything in the commit history related to that, I doubt it.

If it isn't fixed, I guess the only option would be to create a ticket in the upstream repository. Maybe someone there has an idea how to fix that.

**Comment by filipre** [comment] 2021-03-16 20:20
Thanks for the update. I just tried out the new version. The error still happens in native mode but the first warning is gone. This is the updated error. Maybe we should change the title because @gf78's issue happens because of the missing serializer and not because of the `--json` flag. 

```
"error": "WARN ErrorUtils - If you use an Oracle JRE please check if you have unlimited strength crypto enabled, see README
Exception in thread "main" java.lang.AssertionError: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: No serializer found for class org.asamk.signal.json.JsonSyncMessage and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS) (through reference chain: java.util.HashMap["envelope"]->org.asamk.signal.json.JsonMessageEnvelope["syncMessage"])
	at org.asamk.signal.JsonWriter.write(JsonWriter.java:35)
	at org.asamk.signal.JsonReceiveMessageHandler.handleMessage(JsonReceiveMessageHandler.java:35)
	at org.asamk.signal.manager.Manager.receiveMessages(Manager.java:1768)
	at org.asamk.signal.commands.ReceiveCommand.handleCommand(ReceiveCommand.java:165)
	at org.asamk.signal.App.handleLocalCommand(App.java:204)
	at org.asamk.signal.App.init(App.java:164)
	at org.asamk.signal.Main.main(Main.java:49)
Caused by: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: No serializer found for class org.asamk.signal.json.JsonSyncMessage and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS) (through reference chain: java.util.HashMap["envelope"]->org.asamk.signal.json.JsonMessageEnvelope["syncMessage"])
	at com.fasterxml.jackson.databind.SerializerProvider.reportBadDefinition(SerializerProvider.java:1191)
	at com.fasterxml.jackson.databind.DatabindContext.reportBadDefinition(DatabindContext.java:313)
	at com.fasterxml.jackson.databind.ser.impl.UnknownSerializer.failForEmpty(UnknownSerializer.java:71)
	at com.fasterxml.jackson.databind.ser.impl.UnknownSerializer.serialize(UnknownSerializer.java:33)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:727)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:719)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:155)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serializeFields(MapSerializer.java:722)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:643)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:33)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:480)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:319)
	at com.fasterxml.jackson.databind.ObjectMapper._configAndWriteValue(ObjectMapper.java:3906)
	at com.fasterxml.jackson.databind.ObjectMapper.writeValue(ObjectMapper.java:3202)
	at org.asamk.signal.JsonWriter.write(JsonWriter.java:32)
	... 6 more
```

**Comment by filipre** [comment] 2021-04-28 20:07
Hey @bbernhard , https://github.com/AsamK/signal-cli/pull/576 just has been merged fixing the missing serializers in the signal-cli repo. Could you build and release a new version? Then `/receive` should work as well in native mode.

**Comment by bbernhard** [comment] 2021-04-29 20:36
> Hey @bbernhard , [AsamK/signal-cli#576](https://github.com/AsamK/signal-cli/pull/576) just has been merged fixing the missing serializers in the signal-cli repo. Could you build and release a new version? Then `/receive` should work as well in native mode.

Many thanks for the info!

I've just pushed a new `dev` image to dockerhub, based on the commit hash [bda952839244254842d685baceb0d02cd469c944](https://github.com/AsamK/signal-cli/commit/bda952839244254842d685baceb0d02cd469c944). In case you want to give it a try, please use this tag here: `bbernhard/signal-cli-rest-api:0.62-dev`

As soon as signal-cli releases a new version the stable tag will be updated.

**Closed** 2023-11-20 18:48 UTC
