### ISSUE TITLE
can run this docker image on arm64

### ISSUE THREAD

**Issue by malfino** [bbernhard/signal-cli-rest-api#248] opened 2022-06-14 15:50 UTC
### The problem

Hi, I installed this docker image through home assistant on my raspberry pi 4 with ubuntu (arm64). 
uname -m in the docker container says: aarch64

When I check the /var/log/signal-cli-json-rpc-1/out.log
it says:

```
OpenJDK Server VM warning: You have loaded library /tmp/sqlite-3.36.0.3-ac8623a3-aee1-4fa5-a340-971b59c6f6be-libsqlitejdbc.so which might have disabled stack guard. The VM will try to fix the
 stack guard now.
It's highly recommended that you fix the library with 'execstack -c <libfile>', or link it with '-z noexecstack'.
Failed to load native library:sqlite-3.36.0.3-ac8623a3-aee1-4fa5-a340-971b59c6f6be-libsqlitejdbc.so. osinfo: Linux/aarch64
java.lang.UnsatisfiedLinkError: /tmp/sqlite-3.36.0.3-ac8623a3-aee1-4fa5-a340-971b59c6f6be-libsqlitejdbc.so: /tmp/sqlite-3.36.0.3-ac8623a3-aee1-4fa5-a340-971b59c6f6be-libsqlitejdbc.so: wrong E
LF class: ELFCLASS64 (Possible cause: can't load AARCH64 .so on a ARM platform)
ERROR HikariPool - HikariPool-1 - Exception during pool initialization.
java.sql.SQLException: Error opening connection
        at org.sqlite.SQLiteConnection.open(SQLiteConnection.java:244)
        at org.sqlite.SQLiteConnection.<init>(SQLiteConnection.java:61)
        at org.sqlite.jdbc3.JDBC3Connection.<init>(JDBC3Connection.java:28)
        at org.sqlite.jdbc4.JDBC4Connection.<init>(JDBC4Connection.java:21)
        at org.sqlite.JDBC.createConnection(JDBC.java:115)
        at org.sqlite.JDBC.connect(JDBC.java:90)
        at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:121)
        at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:359)
        at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:201)
        at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:470)
        at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:561)
        at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:100)
        at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81)
        at org.asamk.signal.manager.storage.Database.getHikariDataSource(Database.java:94)
        at org.asamk.signal.manager.storage.Database.initDatabase(Database.java:32)
        at org.asamk.signal.manager.storage.AccountDatabase.init(AccountDatabase.java:23)
        at org.asamk.signal.manager.storage.SignalAccount.lambda$getAccountDatabase$21(SignalAccount.java:1062)
        at org.asamk.signal.manager.storage.SignalAccount.getOrCreate(SignalAccount.java:1348)
        at org.asamk.signal.manager.storage.SignalAccount.getAccountDatabase(SignalAccount.java:1060)
        at org.asamk.signal.manager.storage.SignalAccount.initDatabase(SignalAccount.java:263)
        at org.asamk.signal.manager.SignalAccountFiles.initManager(SignalAccountFiles.java:88)
        at org.asamk.signal.manager.SignalAccountFiles.initManager(SignalAccountFiles.java:64)
        at org.asamk.signal.App.loadManager(App.java:337)
        at org.asamk.signal.App.handleLocalCommand(App.java:272)
        at org.asamk.signal.App.init(App.java:213)
        at org.asamk.signal.Main.main(Main.java:58)
Caused by: java.lang.Exception: No native library found for os.name=Linux, os.arch=aarch64, paths=[/org/sqlite/native/Linux/aarch64:/usr/java/packages/lib:/lib:/usr/lib]
        at org.sqlite.SQLiteJDBCLoader.loadSQLiteNativeLibrary(SQLiteJDBCLoader.java:389)
        at org.sqlite.SQLiteJDBCLoader.initialize(SQLiteJDBCLoader.java:68)
        at org.sqlite.core.NativeDB.load(NativeDB.java:63)
        at org.sqlite.SQLiteConnection.open(SQLiteConnection.java:240)
        ... 25 common frames omitted
Error loading state file for user +4xxxxxxx: Failed to initialize pool: Error opening connection (PoolInitializationException)
OpenJDK Server VM warning: You have loaded library /tmp/sqlite-3.36.0.3-16d91112-4326-4d6d-be79-bb44fa1805bb-libsqlitejdbc.so which might have disabled stack guard. The VM will try to fix the
 stack guard now.
It's highly recommended that you fix the library with 'execstack -c <libfile>', or link it with '-z noexecstack'.
Failed to load native library:sqlite-3.36.0.3-16d91112-4326-4d6d-be79-bb44fa1805bb-libsqlitejdbc.so. osinfo: Linux/aarch64
java.lang.UnsatisfiedLinkError: /tmp/sqlite-3.36.0.3-16d91112-4326-4d6d-be79-bb44fa1805bb-libsqlitejdbc.so: /tmp/sqlite-3.36.0.3-16d91112-4326-4d6d-be79-bb44fa1805bb-libsqlitejdbc.so: wrong E
LF class: ELFCLASS64 (Possible cause: can't load AARCH64 .so on a ARM platform)
ERROR HikariPool - HikariPool-1 - Exception during pool initialization.
java.sql.SQLException: Error opening connection
        at org.sqlite.SQLiteConnection.open(SQLiteConnection.java:244)
        at org.sqlite.SQLiteConnection.<init>(SQLiteConnection.java:61)
        at org.sqlite.jdbc3.JDBC3Connection.<init>(JDBC3Connection.java:28)
        at org.sqlite.jdbc4.JDBC4Connection.<init>(JDBC4Connection.java:21)
        at org.sqlite.JDBC.createConnection(JDBC.java:115)
        at org.sqlite.JDBC.connect(JDBC.java:90)
        at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:121)
        at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:359)
        at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:201)
        at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:470)
        at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:561)
        at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:100)
        at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81)
        at org.asamk.signal.manager.storage.Database.getHikariDataSource(Database.java:94)
        at org.asamk.signal.manager.storage.Database.initDatabase(Database.java:32)
        at org.asamk.signal.manager.storage.AccountDatabase.init(AccountDatabase.java:23)
        at org.asamk.signal.manager.storage.SignalAccount.lambda$getAccountDatabase$21(SignalAccount.java:1062)
        at org.asamk.signal.manager.storage.SignalAccount.getOrCreate(SignalAccount.java:1348)
        at org.asamk.signal.manager.storage.SignalAccount.getAccountDatabase(SignalAccount.java:1060)
        at org.asamk.signal.manager.storage.SignalAccount.initDatabase(SignalAccount.java:263)
        at org.asamk.signal.manager.SignalAccountFiles.initManager(SignalAccountFiles.java:88)
        at org.asamk.signal.manager.SignalAccountFiles.initManager(SignalAccountFiles.java:64)
        at org.asamk.signal.App.loadManager(App.java:337)
        at org.asamk.signal.App.handleLocalCommand(App.java:272)
        at org.asamk.signal.App.init(App.java:213)
        at org.asamk.signal.Main.main(Main.java:58)
Caused by: java.lang.Exception: No native library found for os.name=Linux, os.arch=aarch64, paths=[/org/sqlite/native/Linux/aarch64:/usr/java/packages/lib:/lib:/usr/lib]
        at org.sqlite.SQLiteJDBCLoader.loadSQLiteNativeLibrary(SQLiteJDBCLoader.java:389)
        at org.sqlite.SQLiteJDBCLoader.initialize(SQLiteJDBCLoader.java:68)
        at org.sqlite.core.NativeDB.load(NativeDB.java:63)
        at org.sqlite.SQLiteConnection.open(SQLiteConnection.java:240)
        ... 25 common frames omitted
Error loading state file for user +4xxxxxxxx: Failed to initialize pool: Error opening connection (PoolInitializationException)

```
Is there an easy way to fix this?

### Are you using the latest released version?

- [X] Yes

### Have you read the troubleshooting page?

- [X] Yes

### What type of installation are you running?

Home Assistant Signal Addon

### In which mode are you using the docker container?

JSON-RPC Mode

### What's the architecture of your host system?

arm64

**Comment by bbernhard** [comment] 2022-06-14 16:16
> uname -m in the docker container says: aarch64

Do you get the same if you run the command directly on the host system and not inside the docker container?

**Comment by malfino** [comment] 2022-06-16 15:35
Yes

Host:
ubuntu@hass:~$ uname -m
aarch64

container:
root@1315902c-signal-messenger:/data/data# uname -m
aarch64

**Comment by bbernhard** [comment] 2022-06-16 16:28
That's really strange. Unfortunately, I do not have arm64 hardware at hand, so I cannot directly test it. But I just emulated arm64 on my x86-64 machine with QEMU and that is working fine. I also know of a bunch of other users who run it on a Raspberry Pi 4 (with a 64bit OS).

If you have a spare SD card at hand, you could try to install Raspbian (the 64bit version!) and the docker daemon on it and use the `signal-cli-rest-api` docker image directly. That hopefully helps to narrow down the issue.

**Comment by fr1sty** [comment] 2023-04-29 09:34
I'm running into the same problem trying to run this image with docker-compose. Running Libreelec on my Raspberry 4. It has a 64bit kernel with a 32bit userspace. I hope that it's possible to fix this some way, because I really like to use it with my HA integration running on the same system.

**Comment by fr1sty** [comment] 2023-05-04 08:27
Showing the qrlink with http://192.168.0.10:8080/v1/qrcodelink?device_name=signal-api is working though. 
Also when sending a message to a wrong number gives no failure, only a message that the user is not registered. But when changing it to a correct user then the failure stated above comes up.

**Comment by stefanthurnherr** [comment] 2023-12-29 22:19
@malfino @fr1sty Did you find any solution for this issue?

Running into the same issue on my RPi 4 Model B using Raspberry Pi OS, both on bullseye (current OLDSTABLE) and on bookworm (current STABLE). Have tried both signal-cli-rest-api v0.70 and v0.80. 

This problem first occurred when my previous installation stopped working somewhen between 2023-11-29 and 2023-12-01 when my setup started to get http 422 when trying to fetch messages (without any software update from my side). I suspected a change in the signal APIs server-side and since I hadn't upgraded anything for many months I started to upgrade first this docker image and then my RPi OS. With no success.

cat /proc/cpuinfo | grep Model
```
Raspberry Pi 4 Model B Rev 1.5
```

uname -m (on both the host OS and inside the signal-cli-rest-api container)
```
aarch64
```

Here is the stacktrace I'm getting (slightly different to the original stacktrace posted above, but most probably because of newer versions):
```
Got response code 400 : {'error': "OpenJDK Server VM warning: You have loaded library /tmp/sqlite-3.44.0.0-0f003e5b-33ab-4207-964d-0eb278249afc-libsqlitejdbc.so which might have disabled stack guard. The VM will try to fix the stack guard now.
It's highly recommended that you fix the library with 'execstack -c <libfile>', or link it with '-z noexecstack'.
ERROR SQLiteJDBCLoader - Failed to load native library: sqlite-3.44.0.0-0f003e5b-33ab-4207-964d-0eb278249afc-libsqlitejdbc.so. osinfo: Linux/aarch64
java.lang.UnsatisfiedLinkError: /tmp/sqlite-3.44.0.0-0f003e5b-33ab-4207-964d-0eb278249afc-libsqlitejdbc.so: /tmp/sqlite-3.44.0.0-0f003e5b-33ab-4207-964d-0eb278249afc-libsqlitejdbc.so: wrong ELF class: ELFCLASS64 (Possible cause: can't load AARCH64 .so on a ARM platform)
  at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
  at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(Unknown Source)
  at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(Unknown Source)
  at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(Unknown Source)
  at java.base/java.lang.ClassLoader.loadLibrary(Unknown Source)
  at java.base/java.lang.Runtime.load0(Unknown Source)
  at java.base/java.lang.System.load(Unknown Source)
  at org.sqlite.SQLiteJDBCLoader.loadNativeLibrary(SQLiteJDBCLoader.java:266)
  at org.sqlite.SQLiteJDBCLoader.extractAndLoadLibraryFile(SQLiteJDBCLoader.java:223)
  at org.sqlite.SQLiteJDBCLoader.loadSQLiteNativeLibrary(SQLiteJDBCLoader.java:330)
  at org.sqlite.SQLiteJDBCLoader.initialize(SQLiteJDBCLoader.java:75)
  at org.sqlite.core.NativeDB.load(NativeDB.java:69)
  at org.sqlite.SQLiteConnection.open(SQLiteConnection.java:280)
  at org.sqlite.SQLiteConnection.<init>(SQLiteConnection.java:67)
  at org.sqlite.jdbc3.JDBC3Connection.<init>(JDBC3Connection.java:28)
  at org.sqlite.jdbc4.JDBC4Connection.<init>(JDBC4Connection.java:19)
  at org.sqlite.JDBC.createConnection(JDBC.java:106)
  at org.sqlite.JDBC.connect(JDBC.java:79)
  at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:120)
  at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:360)
  at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:202)
  at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:461)
  at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:550)\
  at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:98)
  at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:80)
  at org.asamk.signal.manager.storage.Database.getHikariDataSource(Database.java:101)
  at org.asamk.signal.manager.storage.Database.initDatabase(Database.java:32)
  at org.asamk.signal.manager.storage.AccountDatabase.init(AccountDatabase.java:42)
  at org.asamk.signal.manager.storage.SignalAccount.lambda$getAccountDatabase$22(SignalAccount.java:1225)
  at org.asamk.signal.manager.storage.SignalAccount.getOrCreate(SignalAccount.java:1650)
  at org.asamk.signal.manager.storage.SignalAccount.getAccountDatabase(SignalAccount.java:1223)
  at org.asamk.signal.manager.storage.SignalAccount.lambda$getKeyValueStore$16(SignalAccount.java:1209)
  at org.asamk.signal.manager.storage.SignalAccount.getOrCreate(SignalAccount.java:1650)
  at org.asamk.signal.manager.storage.SignalAccount.getKeyValueStore(SignalAccount.java:1209)
  at org.asamk.signal.manager.storage.SignalAccount.loadLegacyFile(SignalAccount.java:561)
  at org.asamk.signal.manager.storage.SignalAccount.load(SignalAccount.java:446)
  at org.asamk.signal.manager.storage.SignalAccount.load(SignalAccount.java:188)
  at org.asamk.signal.manager.SignalAccountFiles.initManager(SignalAccountFiles.java:97)
  at org.asamk.signal.manager.SignalAccountFiles.initManager(SignalAccountFiles.java:84)
  at org.asamk.signal.App.loadManager(App.java:313)
  at org.asamk.signal.App.handleLocalCommand(App.java:277)
  at org.asamk.signal.App.handleCommand(App.java:179)
  at org.asamk.signal.App.init(App.java:144)
  at org.asamk.signal.Main.main(Main.java:61)
ERROR SQLiteJDBCLoader - Failed to load native library through System.loadLibrary
java.lang.UnsatisfiedLinkError: no sqlitejdbc in java.library.path: /usr/java/packages/lib:/lib:/usr/lib
  at java.base/java.lang.ClassLoader.loadLibrary(Unknown Source)
  at java.base/java.lang.Runtime.loadLibrary0(Unknown Source)
  at java.base/java.lang.System.loadLibrary(Unknown Source)
  at org.sqlite.SQLiteJDBCLoader.loadNativeLibraryJdk(SQLiteJDBCLoader.java:285)
  at org.sqlite.SQLiteJDBCLoader.loadSQLiteNativeLibrary(SQLiteJDBCLoader.java:354)
  at org.sqlite.SQLiteJDBCLoader.initialize(SQLiteJDBCLoader.java:75)
  at org.sqlite.core.NativeDB.load(NativeDB.java:69)
  at org.sqlite.SQLiteConnection.open(SQLiteConnection.java:280)
  at org.sqlite.SQLiteConnection.<init>(SQLiteConnection.java:67)
  at org.sqlite.jdbc3.JDBC3Connection.<init>(JDBC3Connection.java:28)
  at org.sqlite.jdbc4.JDBC4Connection.<init>(JDBC4Connection.java:19)
  at org.sqlite.JDBC.createConnection(JDBC.java:106)
  at org.sqlite.JDBC.connect(JDBC.java:79)
  at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:120)
  at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:360)
  at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:202)
  at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:461)
  at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:550)
  at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:98)
  at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:80)
  at org.asamk.signal.manager.storage.Database.getHikariDataSource(Database.java:101)
  at org.asamk.signal.manager.storage.Database.initDatabase(Database.java:32)
  at org.asamk.signal.manager.storage.AccountDatabase.init(AccountDatabase.java:42)
  at org.asamk.signal.manager.storage.SignalAccount.lambda$getAccountDatabase$22(SignalAccount.java:1225)
  at org.asamk.signal.manager.storage.SignalAccount.getOrCreate(SignalAccount.java:1650)
  at org.asamk.signal.manager.storage.SignalAccount.getAccountDatabase(SignalAccount.java:1223)
  at org.asamk.signal.manager.storage.SignalAccount.lambda$getKeyValueStore$16(SignalAccount.java:1209)
  at org.asamk.signal.manager.storage.SignalAccount.getOrCreate(SignalAccount.java:1650)
  at org.asamk.signal.manager.storage.SignalAccount.getKeyValueStore(SignalAccount.java:1209)
  at org.asamk.signal.manager.storage.SignalAccount.loadLegacyFile(SignalAccount.java:561)
  at org.asamk.signal.manager.storage.SignalAccount.load(SignalAccount.java:446)
  at org.asamk.signal.manager.storage.SignalAccount.load(SignalAccount.java:188)
  at org.asamk.signal.manager.SignalAccountFiles.initManager(SignalAccountFiles.java:97)
  at org.asamk.signal.manager.SignalAccountFiles.initManager(SignalAccountFiles.java:84)
  at org.asamk.signal.App.loadManager(App.java:313)
  at org.asamk.signal.App.handleLocalCommand(App.java:277)
  at org.asamk.signal.App.handleCommand(App.java:179)
  at org.asamk.signal.App.init(App.java:144)
  at org.asamk.signal.Main.main(Main.java:61)
Error loading state file for user +4xxxxxxxxxx: Failed to initialize pool: Error opening connection (PoolInitializationException)
"}
```

**Comment by malfino** [comment] 2023-12-30 07:10
It was a problem with the premade docker image. I installed it manually and then it worked.

**Comment by stefanthurnherr** [comment] 2023-12-31 16:06
Thanks @malfino, I am trying to build the docker image myself on my aarch64 RPi using these steps:
1. git clone 
2. cd signal-cli-rest-api
3. docker build -t <my own local-tag> .

[The code in the Dockerfile](https://github.com/bbernhard/signal-cli-rest-api/blob/7fcb70e673aa7189bfe5330b1e62077ad9d00957/Dockerfile#L94C16-L94C54) for including signal-cli library for aarch64 architecture seems broken:

I changed the line to this [as per the instructions](https://packaging.gitlab.io/signal-cli/installation/standalone/#add-repo-to-apt):
```
https://github.com/bbernhard/signal-cli-rest-api/blob/7fcb70e673aa7189bfe5330b1e62077ad9d00957/Dockerfile#L94C16-L94C54
```
But I am still getting this error when trying to build the image on my aarch64 RPi:
```
[...]
0.454 Use native image from @morph027 (https://packaging.gitlab.io/signal-cli/) for arm64 - many thanks to @morph027
0.603 Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).
3.744 OK
13.16 E: Unable to locate package signal-cli-native
```

@morph027 Is this [documentation](https://packaging.gitlab.io/signal-cli/installation/standalone/#add-repo-to-apt) still up-to-date?
````
echo "deb https://packaging.gitlab.io/signal-cli signalcli main" | sudo tee /etc/apt/sources.list.d/morph027-signal-cli.list
sudo apt-get install signal-cli-<jre|native> morph027-keyring
```

**Comment by morph027** [comment] 2023-12-31 19:17
Hm .... works here in a test container:

![image](https://github.com/bbernhard/signal-cli-rest-api/assets/600106/531dc0f4-54b4-406c-833e-f01602d248bb)

**Comment by stefanthurnherr** [comment] 2024-01-01 15:58
When specifying an arch filter `deb [arch=arm64] https://...` in the sources list and then running `apt-cache search signal-cli` I get this output:
```
21.36 signal-cli-dbus-service - signal-cli provides an unofficial commandline and dbus interface for signalapp/libsignal-service-java - DBus system service
21.36 signal-cli-service - signal-cli provides an unofficial commandline and dbus interface for signalapp/libsignal-service-java - system service
´´´

However I would expect all the packages provided by your deb repo.

Looking at the [Packages](https://packaging.gitlab.io/signal-cli/dists/signalcli/main/binary-arm64/Packages) specification for binary-arm64 in the signal-cli deb repo, the difference is that the two packages found by apt-cache search above specify `Architecture: all` whereas the `signal-cli-native/jre` packages specify `Architecture: arm64`. So I suspect some arch mismatch. I have tried to read up on how architectures work in apt but cannot seem to solve this. `uname -m`gives `aarch64`, and `dpkg --print-foreign-architectures` does not print out anything so I assume apt only takes into account the actual architecture of the OS. And I assume that aarch64 and arm64 are treated as being the same arch.

I will try to build the docker image by downloading the deb package manually instead, the Dockerfile has already some commented-out lines using a similar workaround:
```
wget https://packaging.gitlab.io/signal-cli/pool/main/s/signal-cli-native/signal-cli-native_0.12.7+2_arm64.deb
```

**Comment by morph027** [comment] 2024-01-01 17:46
Hm, right, that's weird. It is the proper architecture (compared to any other package like `apt-cache show vim`) Not sure, whats messed up there. The repo itself is being maintained w/ reprepro

**Comment by stefanthurnherr** [comment] 2024-01-01 21:13
`dpkg --print-architecture` prints `armhf` so is different from `uname -m` which prints `aarch64` (both on the host OS and inside the docker container). I suspect this is because I upgraded from bullseye to bookworm using apt (changing the URLs in the deb sources list). I will probably try to re-install bookworm from scratch instead.

**Comment by stefanthurnherr** [comment] 2024-01-03 18:11
I can confirm that after doing a clean install of latest RPi OS Desktop (bookworm), the docker image from docker hub works like a charm.
In my case the problem was that I upgraded from bullseye to bookworm on a 64-bit RPi 4, and the upgrade messed up the architectures of the installed deb packages. No wonder, since upgrading is not recommended generally, doing a clean install is strongly recommended.

If you run into similar problems when running (or building) the docker image on a 64-bit RPi, make sure that both these commands print correct values:
* `uname -m` should print `aarch64`
* `dpkg --print-architecture` should print `arm64`

**Comment by bbernhard** [comment] 2024-02-21 17:52
As the issue was created a long time ago, I'll close this one now. In case anyone still experiences any issues, please create a new issue.

**Closed by bbernhard** 2024-02-21 17:52 UTC
