### ISSUE TITLE
Add support for multi-mode CLI

### ISSUE THREAD

**Issue by xSAVIKx** [bbernhard/signal-cli-rest-api#354] opened 2023-04-06 14:01 UTC
### Feature Request

So I've stumbled across an issue with the RPC API limitations regarding registering/linking phones using QR codes. What I have in mind though is that it probably should be possible to have a fallback when running the container in JSON RPC mode to native/standard mode to perform some commands that are not supported by the JSON RPC.

So the feature request is exactly like that :-) Allow having a `MIXED` JSON-RPC/NORMAL mode where unsupported RPC commands are processed using NORMAL/NATIVE mode CLI. I'm not fully aware of how CLI works exactly under the hood, but I guess we start a CLI daemon to which the REST API then propagates commands, so it should probably be possible to start another CLI nearby in a different mode, propagate a non-supported command and then shut it down.

I'm happy to assist with such an implementation, but I'm no expert in Go. Any feedback is highly appreciated as I have to solve this one or another way soon.

**Comment by bbernhard** [comment] 2023-04-13 13:18
Thanks for the suggestion! But I am afraid, that is not easily possible.

The problem is, that `signal-cli` locks the signal-cli-config file (presumably to avoid file corruptions and race conditions when multiple instances try to access the file). So, while `signal-cli` is running in json-rpc mode, it locks the file and no other `signal-cli` instance can access it. In order to implement the suggested `MIXED` mode, we would first need to shut down the signal-cli instance that is running in `json-rpc` mode before we can run a command in normal/native mode. After that we need to start `signal-cli` in json-rpc mode again. While this is certainly doable, it has one big downside: If some client has a websocket connection established, the connection would be closed and the client has to re-establish the connection again.

**Comment by filipre** [comment] 2023-08-30 19:38
Hey @bbernhard, I was wondering what the exact reason is why *some* methods are only available in `normal` or `native` mode such as linking your device. What would it take to port this function in particular to the `json-rpc` if the mixed mode is out of reach? Could you provide some pointers on how to implement this?

**Comment by bbernhard** [comment] 2023-08-31 19:54
That is a limitation of signal-cli. Registering a number/Linking a new device isn't possible in json-rpc mode.

**Comment by filipre** [comment] 2023-08-31 20:25
Thank you. I even found a comment from you 2 years ago on the same topic [here](https://github.com/AsamK/signal-cli/discussions/679#discussioncomment-1308612). I'll ask over there :)

**Comment by filipre** [comment] 2023-09-01 16:10
The author of signal-cli added the functionality [today](https://github.com/AsamK/signal-cli/issues/1319#issuecomment-1702515234) and it will be released in the next version 🍾. He also updated the [docs](https://github.com/AsamK/signal-cli/blob/master/man/signal-cli-jsonrpc.5.adoc). Is this sufficient for implementing the endpoint or is there something else missing from signal-cli?

**Comment by bbernhard** [comment] 2023-09-02 13:54
Sounds good! I'll have a look once it is released

**Comment by filipre** [comment] 2023-10-04 07:15
It has been released: https://github.com/AsamK/signal-cli/releases/tag/v0.12.2

**Comment by bbernhard** [comment] 2023-11-22 19:56
This will be implemented in the next release. If you want to help with testing, please have a look here: https://github.com/bbernhard/signal-cli-rest-api/discussions/454

**Comment by bbernhard** [comment] 2023-12-20 20:54
should be implemented now

**Closed by bbernhard** 2023-12-20 20:54 UTC
