### ISSUE TITLE
Unable to get group_id

### ISSUE THREAD

**Issue by Oleks1y** [bbernhard/signal-cli-rest-api#423] opened 2023-10-07 23:49 UTC
### The problem

I use the following request:

curl -X GET -H "Content-Type: application/json" 'http://127.0.0.1:8080/v1/groups/+4XXXXXXXX'

and I have the following error 
{"error":"invalid character 'I' looking for beginning of value"}%  

### Are you using the latest released version?

- [X] Yes

### Have you read the troubleshooting page?

- [X] Yes

### What type of installation are you running?

signal-cli-rest-api Docker Container

### In which mode are you using the docker container?

Native Mode

### What's the architecture of your host system?

arm64

**Comment by bbernhard** [comment] 2023-10-09 19:19
Please do [this](https://github.com/bbernhard/signal-cli-rest-api/blob/master/doc/DEBUG.md) and post the (obfuscated!) output here.

**Comment by smaktacular** [comment] 2023-10-13 09:34
The command in used was:
`signal-cli --config /home/.local/share/signal-cli --output json -a <number> listGroups -d`

**Comment by bbernhard** [comment] 2023-10-13 10:18
yeah, that info message shouldn't cause any endpoint to fail. That is a bug and will be fixed. But the root cause is, that you need to call the `receive` endpoint regularily (in normal/native mode). Otherwise it doesn't work properly. So, either call the `receive` endpoint regularily yourself, or use the `Auto Receive Schedule` (see the documentation for details)

**Comment by bbernhard** [comment] 2023-10-28 13:57
should be fixed with the latest release

**Closed by bbernhard** 2023-10-28 13:57 UTC
