### ISSUE TITLE
getting groups / groupmembers exception (0.38 in native mode) 

### ISSUE THREAD

**Issue by hvdort** [bbernhard/signal-cli-rest-api#134] opened 2021-05-17 20:30 UTC
First of all: excellent work!

I receive an exception when calling list groups (after adding some members to a group using the app on my phone):

{"error":"Exception in thread \"main\" java.lang.RuntimeException: Field groupMasterKey_ for org.signal.storageservice.protos.groups.GroupInviteLink$GroupInviteLinkContentsV1 not found. Known fields are []\n\tat com.google.protobuf.MessageSchema.reflectField(MessageSchema.java:608)\n\tat com.google.protobuf.MessageSchema.newSchemaForRawMessageInfo(MessageSchema.java:502)\n\tat com.google.protobuf.MessageSchema.newSchema(MessageSchema.java:221)\n\tat com.google.protobuf.ManifestSchemaFactory.newSchema(ManifestSchemaFactory.java:85)\n\tat com.google.protobuf.ManifestSchemaFactory.createSchema(ManifestSchemaFactory.java:71)\n\tat com.google.protobuf.Protobuf.schemaFor(Protobuf.java:93)\n\tat com.google.protobuf.Protobuf.schemaFor(Protobuf.java:107)\n\tat com.google.protobuf.GeneratedMessageLite.makeImmutable(GeneratedMessageLite.java:170)\n\tat com.google.protobuf.GeneratedMessageLite$Builder.buildPartial(GeneratedMessageLite.java:386)\n\tat com.google.protobuf.GeneratedMessageLite$Builder.build(GeneratedMessageLite.java:394)\n\tat org.signal.storageservice.protos.groups.GroupInviteLink.setV1Contents(GroupInviteLink.java:402)\n\tat org.signal.storageservice.protos.groups.GroupInviteLink.access$900(GroupInviteLink.java:9)\n\tat org.signal.storageservice.protos.groups.GroupInviteLink$Builder.setV1Contents(GroupInviteLink.java:566)\n\tat org.asamk.signal.manager.groups.GroupInviteLinkUrl.createUrl(GroupInviteLinkUrl.java:101)\n\tat org.asamk.signal.manager.groups.GroupInviteLinkUrl.\u003cinit\u003e(GroupInviteLinkUrl.java:96)\n\tat org.asamk.signal.manager.groups.GroupInviteLinkUrl.forGroup(GroupInviteLinkUrl.java:26)\n\tat org.asamk.signal.manager.storage.groups.GroupInfoV2.getGroupInviteLink(GroupInfoV2.java:72)\n\tat org.asamk.signal.commands.ListGroupsCommand.handleCommand(ListGroupsCommand.java:80)\n\tat org.asamk.signal.App.handleLocalCommand(App.java:211)\n\tat org.asamk.signal.App.init(App.java:./stuurbericht.sh

**Comment by bbernhard** [comment] 2021-05-19 20:00
Do you know if the issue appeared after you've added the members to the group? Could you maybe try to call the receive endpoint (i.e `curl -X GET -H "Content-Type: application/json" 'http://127.0.0.1:8080/v1/receive/<your number>'` and try the list groups endpoint afterwards again. Does that fix the issue?

**Comment by hvdort** [comment] 2021-05-22 20:36
No, it did not fix the issue.
It still appears, also after calling the receive command multiple times until no output.

**Comment by bbernhard** [comment] 2021-05-23 20:44
Does the error only appear with the native mode or also in non-native mode? Whats the host architecture of your system? Could you maybe try to update the docker image to v0.39 (which was released yesterday) to check whether that fixes the issue.

**Comment by haberda** [comment] 2021-05-24 15:00
@hvdort @bbernhard Hello, I am seeing the same thing on amd64 while using native mode. This is using the hassio add-on based on 0.37. I haven't updated the add-on yet because I cannot get native mode to work at all (meaning no sent messages from Home Assistant) on 0.38 or 0.39 on amd64. I haven't had the time to test other platforms or do an in depth test with the CLI on versions 0.38 or 0.39.

With native mode disabled, the add-on based on version 0.38 and 0.39 both worked fine. I'll try and see if I can test more soon.

**Comment by haberda** [comment] 2021-05-25 13:43
When I try and send a message on 0.39 with native mode enabled on an amd64 platform I get this error:

```{"error":"Error loading state file for user <number>: Cannot construct instance of `org.asamk.signal.manager.storage.protocol.LegacyJsonSignalProtocolStore` (no Creators, like default construct, exist): cannot deserialize from Object value (no delegate- or property-based Creator)\n at [Source: UNKNOWN; line: -1, column: -1] (IllegalArgumentException)\n"}```

However, with native mode disabled the message seems to send fine.

**Comment by bbernhard** [comment] 2021-05-25 14:44
That's strange. Haven't seen any major issues with the native mode on amd64 so far.

> Rolling back to 0.37 works again.

Does 0.37 also work with the native mode?

**Comment by hvdort** [comment] 2021-05-25 17:16
> @hvdort @bbernhard Hello, I am seeing the same thing on amd64 while using native mode. This is using the hassio add-on based on 0.37. I haven't updated the add-on yet because I cannot get native mode to work at all (meaning no sent messages from Home Assistant) on 0.38 or 0.39 on amd64. I haven't had the time to test other platforms or do an in depth test with the CLI on versions 0.38 or 0.39.
> 
> With native mode disabled, the add-on based on version 0.38 and 0.39 both worked fine. I'll try and see if I can test more soon.

I have the same experience. Native mode gives the problem. Disabling this solves the problem. Upgrade to 0.39 same results.

My error begins with {"error":"Exception in thread "main" java.lang.RuntimeException: Field groupMasterKey_ for org.signal.storageservice.protos.groups.GroupInviteLink$GroupInviteLinkContentsV1 not found

**Comment by bbernhard** [comment] 2021-05-25 17:39
> I have the same experience. Native mode gives the problem. Disabling this solves the problem. Upgrade to 0.39 same results. I run this on amd64.
> 
> My error begins with {"error":"Exception in thread "main" java.lang.RuntimeException: Field groupMasterKey_ for org.signal.storageservice.protos.groups.GroupInviteLink$GroupInviteLinkContentsV1 not found

I think your error has a different root cause than the one @haberda is experiencing. At the moment I am fairly certain, that this is a [signal-cli](https://github.com/AsamK/signal-cli) issue. But opening a ticket there probably isn't that helpful, until we figure out what causes the issue. I just tried again here in my local test setup, but unfortunately can't reproduce the issue here. 

Could you maybe post the output of the `list groups` endpoint here (without the native mode). Please don't forget to obfuscate any personal information (like phone numbers)! Maybe that gives us some clue about the state of your signal-cli instance.

Do you remember what you've done before the groups endpoint stopped working? Did you create the Signal Group with your phone or with the REST API? Did you add any members later on? Maybe I can reproduce the issue here by doing the same steps you did in your setup.

**Comment by hvdort** [comment] 2021-05-25 17:55
Getting the groups using non-native, the results are (anonymized):

[{"name":"testgroep","id":"group.V2NZaUFCVTF...............dk0wWFpjV3dMSm5tWjI2VT0=","internal_id":"WcYiABU...................ZcWwLJnmZ26U=","members":["+316*000****","+316*199****"],"blocked":false,"pending_invites":[],"pending_requests":[],"invite_link":"https://signal.group/#CjQKIN2N0VJXnWL.................................hessDsu42KFeyh2oJo5"},{"name":"family group","id":"group.U0V3cWIyWDJKaFB.....................XZkdNYjhPdz0=","internal_id":"SEwqb2X2J.....................S0Fy1WfGMb8Ow=","members":["+316*087****","+316*230****","+316*000****","+316*322****","+316*847****","+316*737****","+316*606****","+316*532****","+316*508****","+316*440****","+316*046****"],"blocked":false,"pending_invites":[],"pending_requests":[],"invite_link":""}]

I see my testgroup begins with "group.V2...". Maybe relevant while the error says: ...ContentsV1?
The problem has begun after creating the testgroup using my phone. The docker container is linked to my instance on my phone using the qr picture. The family group does exists earlier. I hope this can help to reproduce and solve this problem :-)

**Comment by bbernhard** [comment] 2021-05-25 18:03
>I see my testgroup begins with "group.V2...". Maybe relevant while the error says: ...ContentsV1?

I am not an expert, but as far as I know Signal falls back to a V1 group in case there's at least one group member that doesn't have an up to date app with group v2 support. Could that maybe be the case? 

I guess that might be the reason why I can't trigger the issue in my test environment.

**Comment by haberda** [comment] 2021-05-25 18:47
> 
> 
> That's strange. Haven't seen any major issues with the native mode on amd64 so far.
> 
> > Rolling back to 0.37 works again.
> 
> Does 0.37 also work with the native mode?

Yes, 0.37 works in terms of sending messages with native mode. However, querying the groups endpoint fails with native mode enabled even on 0.37.

**Comment by bbernhard** [comment] 2021-05-25 19:05
> > That's strange. Haven't seen any major issues with the native mode on amd64 so far.
> > > Rolling back to 0.37 works again.
> > 
> > 
> > Does 0.37 also work with the native mode?
> 
> Yes, 0.37 works in terms of sending messages with native mode. However, querying the groups endpoint fails with native mode enabled even on 0.37.

If I remember correctly, there were some issues in signal-cli with the groups listing and the native mode. It's likely that it wasn't working at all in version 0.37.

Do you maybe have a prebuilt docker image somewhere that I could give a try?

**Comment by haberda** [comment] 2021-05-25 21:58
> 
> 
> > > That's strange. Haven't seen any major issues with the native mode on amd64 so far.
> > > > Rolling back to 0.37 works again.
> > > 
> > > 
> > > Does 0.37 also work with the native mode?
> > 
> > 
> > Yes, 0.37 works in terms of sending messages with native mode. However, querying the groups endpoint fails with native mode enabled even on 0.37.
> 
> If I remember correctly, there were some issues in signal-cli with the groups listing and the native mode. It's likely that it wasn't working at all in version 0.37.
> 
> Do you maybe have a prebuilt docker image somewhere that I could give a try?

Yes, I repackage your container with the requirements for the add-on and host it here: https://hub.docker.com/r/eightiesguy/signal-addon

I have the Dockerfile here: https://github.com/haberda/signal-addon

It might have some trouble starting outside of Home Assistant, the reason being is it expects a file at: /data/options.json

I'll upload a sample options.json to the Dockerfile repo. The json just tells a script whether or not to enable native_mode or the new automated retrieval added in 0.38. So just mount the json in the /data folder and it should work, I think.

**Comment by bbernhard** [comment] 2021-05-26 15:06
> > > > That's strange. Haven't seen any major issues with the native mode on amd64 so far.
> > > > > Rolling back to 0.37 works again.
> > > > 
> > > > 
> > > > Does 0.37 also work with the native mode?
> > > 
> > > 
> > > Yes, 0.37 works in terms of sending messages with native mode. However, querying the groups endpoint fails with native mode enabled even on 0.37.
> > 
> > 
> > If I remember correctly, there were some issues in signal-cli with the groups listing and the native mode. It's likely that it wasn't working at all in version 0.37.
> > Do you maybe have a prebuilt docker image somewhere that I could give a try?
> 
> Yes, I repackage your container with the requirements for the add-on and host it here: https://hub.docker.com/r/eightiesguy/signal-addon
> 
> I have the Dockerfile here: https://github.com/haberda/signal-addon
> 
> It might have some trouble starting outside of Home Assistant, the reason being is it expects a file at: /data/options.json
> 
> I'll upload a sample options.json to the Dockerfile repo. The json just tells a script whether or not to enable native_mode or the new automated retrieval added in 0.38. So just mount the json in the /data folder and it should work, I think.

I just tried it and it seems to work for me (as I do not have any experience with Home Assistant addons, I just used the plain docker image). My assumption is that there's something wrong with the path to the signal-cli config file in your setup. 

When you run the Home Assistant addon, do you have access to the docker logs and is it possible to connect to the running docker container? If so, you could do the following.

* Enable the debug logging with `curl -X POST -H "Content-Type: application/json" -d '{"logging": {"level": "debug"}}' 'http://127.0.0.1:8080/v1/configuration'`
* Perform any action (e.g send a message)
* Have a look at the container log file, you should see something like this:

```
signal-cli-rest-api_1  | time="2021-05-26T14:59:13Z" level=debug msg="If you want to run this command manually, run the following steps on your host system:"
signal-cli-rest-api_1  | time="2021-05-26T14:59:13Z" level=debug msg="*) docker exec -it 8a3f2d1b6ce20ba4dffafc0427aab3db797a7e060e34d74fa13b209e587fdc14 /bin/bash"
signal-cli-rest-api_1  | time="2021-05-26T14:59:13Z" level=debug msg="*) su signal-api"
signal-cli-rest-api_1  | time="2021-05-26T14:59:13Z" level=debug msg="*) signal-cli-native --config /home/.local/share/signal-cli -u +43xxxxxxx send +43xxxxxxx -m test"
```

* Connect to the docker container and run the commands that are mentioned in the log file (the `signal-cli`/`signal-cli-native` command that's shown is the exact command that was executed by the REST API wrapper). According to the message you've posted above my assumption would be that the path specified via the `--config` parameter is maybe not the correct one.

**Comment by haberda** [comment] 2021-05-27 18:13
When I attempt to send a message from Home Assistant with native enabled and the enhanced logging you suggested I basically get the same output you have with one exception:

```
time="2021-05-27T10:54:05-07:00" level=debug msg="*) signal-cli-native --config /data -u +<fromnum> send +<tonum>"
```

I tried to send a message that just said "test" but if you note in the above, there is no "-m test".

When I copy and paste the command as suggested into the docker console I get this output:

```
Error loading state file for user +<fromnum>: Cannot construct instance of 'org.asamk.signal.manager.storage.protocol.LegacyJsonSignalProtocolStore' (no Creators, like default construct, exist): cannot deserialize from Object value (no delegate- or property-based Creator)
 at [Source: UNKNOWN; line: -1, column: -1] (IllegalArgumentException)
```
This happens even when I add `-m test`

When I try the same with native mode disabled, the message sends fine and the output in the console looks good too.

**Comment by bbernhard** [comment] 2021-05-27 18:25
aaah, sorry, there's something missing in the log output (I'll fix that with the next build). It should be:

```echo "test" | signal-cli-native --config /data -u +<fromnum> send +<tonum>```

So you basically pipe the text you want to send to the `signal-cli`/`signal-cli-native` instance. 

When you connected to the docker container, do you see the signal-cli config inside the `/data` folder? There should be a file named `+<fromnum>` in the `/data/data` folder.

**Comment by bbernhard** [comment] 2021-05-27 18:35
btw: this here looks a bit related at first glance: https://github.com/AsamK/signal-cli/issues/616 (except that you are experiencing the issues with the native mode).

Maybe you get some additional output with the `--verbose` flag?

**Comment by haberda** [comment] 2021-05-27 19:28
Yes the statefile is indeed in `/data/data`

When I run `echo "test" | signal-cli-native --verbose --config /data -u +<fromnum> send +<tonum>` with a verbose flag I get this output:
```
2021-05-27T12:14:27.492-0700 [main] DEBUG org.asamk.signal.App - Loading state file failed
java.lang.IllegalArgumentException: Cannot construct instance of `org.asamk.signal.manager.storage.protocol.LegacyJsonSignalProtocolStore` (no Creators, like default construct, exist): cannot deserialize from Object value (no delegate- or property-based Creator)
 at [Source: UNKNOWN; line: -1, column: -1]
        at com.fasterxml.jackson.databind.ObjectMapper._convert(ObjectMapper.java:3751)
        at com.fasterxml.jackson.databind.ObjectMapper.convertValue(ObjectMapper.java:3669)
        at org.asamk.signal.manager.storage.SignalAccount.load(SignalAccount.java:413)
        at org.asamk.signal.manager.storage.SignalAccount.load(SignalAccount.java:113)
        at org.asamk.signal.manager.Manager.init(Manager.java:291)
        at org.asamk.signal.App.loadManager(App.java:248)
        at org.asamk.signal.App.handleLocalCommand(App.java:210)
        at org.asamk.signal.App.init(App.java:171)
        at org.asamk.signal.Main.main(Main.java:51)
Caused by: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `org.asamk.signal.manager.storage.protocol.LegacyJsonSignalProtocolStore` (no Creators, like default construct, exist): cannot deserialize from Object value (no delegate- or property-based Creator)
 at [Source: UNKNOWN; line: -1, column: -1]
        at com.fasterxml.jackson.databind.DeserializationContext.reportBadDefinition(DeserializationContext.java:1452)
        at com.fasterxml.jackson.databind.DeserializationContext.handleMissingInstantiator(DeserializationContext.java:1028)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1297)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:326)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:159)
        at com.fasterxml.jackson.databind.ObjectMapper._convert(ObjectMapper.java:3746)
        ... 8 more
Error loading state file for user +<sendnum>: Cannot construct instance of `org.asamk.signal.manager.storage.protocol.LegacyJsonSignalProtocolStore` (no Creators, like default construct, exist): cannot deserialize from Object value (no delegate- or property-based Creator)
 at [Source: UNKNOWN; line: -1, column: -1] (IllegalArgumentException)
```

Alternatively, when I run `echo "test" | signal-cli --verbose --config /data -u +<fromnum> send +<tonum>` the message sends fine and I get:

```
2021-05-27T12:18:20.736-0700 [main] DEBUG org.asamk.signal.manager.storage.recipients.RecipientStore - Creating new recipient store.
2021-05-27T12:18:20.739-0700 [main] DEBUG org.asamk.signal.manager.storage.SignalAccount - Migrating legacy recipient store.
2021-05-27T12:18:20.754-0700 [main] DEBUG org.asamk.signal.manager.storage.recipients.RecipientStore - Got new recipient, both uuid and number are unknown
2021-05-27T12:18:20.763-0700 [main] DEBUG org.asamk.signal.manager.storage.recipients.RecipientStore - Got new recipient, both uuid and number are unknown
2021-05-27T12:18:20.763-0700 [main] DEBUG org.asamk.signal.manager.storage.recipients.RecipientStore - Got new recipient, both uuid and number are unknown
2021-05-27T12:18:20.764-0700 [main] DEBUG org.asamk.signal.manager.storage.SignalAccount - Migrating legacy pre key store.
2021-05-27T12:18:20.770-0700 [main] DEBUG org.asamk.signal.manager.storage.SignalAccount - Migrating legacy signed pre key store.
2021-05-27T12:18:20.770-0700 [main] DEBUG org.asamk.signal.manager.storage.SignalAccount - Migrating legacy session store.
2021-05-27T12:18:20.776-0700 [main] DEBUG org.asamk.signal.manager.storage.SignalAccount - Migrating legacy identity session store.
2021-05-27T12:18:20.778-0700 [main] DEBUG org.asamk.signal.manager.storage.SignalAccount - Migrating legacy contact store.
2021-05-27T12:18:20.786-0700 [main] DEBUG org.asamk.signal.manager.storage.SignalAccount - Migrating legacy profile store.
2021-05-27T12:18:21.713-0700 [main] WARN LibSignal - [PhoneNumberFormatter]: Got local CC: US
2021-05-27T12:18:21.715-0700 [main] INFO LibSignal - [WebSocketConnection]: connect()
2021-05-27T12:18:21.719-0700 [main] INFO LibSignal - [WebSocketConnection]: connect()
2021-05-27T12:18:21.870-0700 [main] WARN LibSignal - [SignalServiceMessageSender]: No attachments present...
2021-05-27T12:18:21.911-0700 [main] WARN LibSignal - [SignalServiceMessageSender]: java.io.IOException: No connection!
        at org.whispersystems.signalservice.internal.websocket.WebSocketConnection.sendRequest(WebSocketConnection.java:206)
        at org.whispersystems.signalservice.api.SignalServiceMessagePipe.send(SignalServiceMessagePipe.java:194)
        at org.whispersystems.signalservice.api.SignalServiceMessageSender.sendMessage(SignalServiceMessageSender.java:1553)
        at org.whispersystems.signalservice.api.SignalServiceMessageSender.sendMessage(SignalServiceMessageSender.java:316)
        at org.asamk.signal.manager.Manager.sendMessage(Manager.java:1485)
        at org.asamk.signal.manager.Manager.sendMessage(Manager.java:1419)
        at org.asamk.signal.manager.Manager.sendMessage(Manager.java:1053)
        at org.asamk.signal.dbus.DbusSignalImpl.sendMessage(DbusSignalImpl.java:97)
        at org.asamk.signal.commands.SendCommand.handleCommand(SendCommand.java:121)
        at org.asamk.signal.commands.DbusCommand.handleCommand(DbusCommand.java:15)
        at org.asamk.signal.App.handleLocalCommand(App.java:211)
        at org.asamk.signal.App.init(App.java:171)
        at org.asamk.signal.Main.main(Main.java:51)

2021-05-27T12:18:21.912-0700 [main] WARN LibSignal - [SignalServiceMessageSender]: [sendMessage] Unidentified pipe failed, falling back...
2021-05-27T12:18:22.073-0700 [OkHttp https://textsecure-service.whispersystems.org/...] INFO LibSignal - [WebSocketConnection]: onOpen() connected
2021-05-27T12:18:22.073-0700 [OkHttp https://textsecure-service.whispersystems.org/...] INFO LibSignal - [WebSocketConnection]: onOpen() connected
<maybe secret number>
2021-05-27T12:18:22.287-0700 [main] INFO LibSignal - [WebSocketConnection]: disconnect()
2021-05-27T12:18:22.290-0700 [main] INFO LibSignal - [WebSocketConnection]: disconnect()

```

Something else of note, if I follow the symlink to where the signal-cli binaries live in `/opt/signal-cli-0.8.3/bin` it looks like the signal-cli has a modification date on Jan 1 1970; whereas the signal-cli-native has a mod date of May 22 2021.

**Comment by bbernhard** [comment] 2021-05-28 14:44
I think the modification time is a red herring. I've checked the modification date of `signal-cli` and `signal-cli-native` inside the docker container I am using and I am seeing the same here. I _think_ the system date wasn't correctly set when `signal-cli` was built for the docker image, so it defaulted to the beginning of the unix time epoch (i.e `1970-01-01`). I have to check why that happens, but apart from the wrong modification timestamp the binary should be fine.

Do you see the `Migrating legacy pre key store.` debug output every time you run a `signal-cli` command? Unfortunately, I do not know much about the internals of `signal-cli`, so I do not know whether that migration happens every time or if the migrated profile will be persisted somewhere. In case you haven't tried it yet: Calling the `receive` endpoint (with disabled native mode!) fixed some profile issues for me in the past. So that might be worth a try. Please make sure to run the `receive` endpoint with the new docker image (version 0.38 or version 0.39) and not the old one. 

Apart from that, I think I am running out of ideas. To me it looks like as it's related to the profile migration, which maybe isn't correctly handled in the native mode? I guess it might be worth to create a ticket in the [signal-cli](https://github.com/AsamK/signal-cli) repository posting both `signal-cli` calls and the different output you got. Maybe that helps tracking down the issue. 

In case the issue can't be fixed upstream you could try to delete the config on the filesystem and start from scratch by registering your device again. (I did that a few times in the past whenever I've messed something up while developing and it always fixed the issue for me).

**Comment by haberda** [comment] 2021-05-29 22:05
FYI, I opened a ticket over at signal-cli. I tried to delete my statefile and start over but no luck. It may just be an issue with the amd64 instance. As always, thanks for the help.

**Comment by haberda** [comment] 2021-06-03 16:00
For clarity, I got it to work by deleting everything in the persistent storage and starting over.

**Comment by bbernhard** [comment] 2021-12-31 22:00
should be fixed. Please re-open in case it still persists.

**Closed by bbernhard** 2021-12-31 22:00 UTC
